'use strict';
(() => {
const $=id=>document.getElementById(id);
const data=JSON.parse($('property-data').textContent),validation=JSON.parse($('validation-data').textContent);
const engine=AmmoniaEngine.createEngine(data);
const ATM=1.01325,PSI=14.503773773,STORAGE='ammonia-lab-scenarios-v020';
const DEFAULT_UNITS={p:'psig',T:'F'};
let units={...DEFAULT_UNITS},applied={...engine.defaults},result=null,step=0,paused=false,roomResult=null,scenarios=[],compared=new Set();
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(n,d=1)=>Number.isFinite(n)?n.toFixed(d):'—';
const pLabel=()=>({bara:'bar(a)',barg:'bar(g)',psia:'psia',psig:'psig'})[units.p];
const pDisplay=(p,u=units.p,delta=false)=>(p-(!delta&&u.endsWith('g')?ATM:0))*(u.startsWith('psi')?PSI:1);
const pInternal=(p,u=units.p,delta=false)=>p/(u.startsWith('psi')?PSI:1)+(!delta&&u.endsWith('g')?ATM:0);
const tDisplay=(t,u=units.T,delta=false)=>u==='F'?t*1.8+(delta?0:32):t;
const tInternal=(t,u=units.T,delta=false)=>u==='F'?(t-(delta?0:32))/1.8:t;
const pt=p=>fmt(pDisplay(p),units.p.startsWith('psi')?2:3)+' '+pLabel();
const tt=t=>fmt(tDisplay(t),1)+' °'+units.T;
const deltaText=t=>fmt(tDisplay(t,units.T,true),1)+(units.T==='F'?' °F Δ':' K');
const pKeys=['pressure','condensing'],dpKeys=['suctionDrop','liquidDrop'],tKeys=['ambient','spaceTemp','dischargeLimit'],dtKeys=['approach','evapSH','lineSH','subcool'];
const allNumeric=Object.keys(engine.defaults).filter(k=>typeof engine.defaults[k]==='number');
function fieldDisplay(key,v){if(pKeys.includes(key))return pDisplay(v);if(dpKeys.includes(key))return pDisplay(v,units.p,true);if(tKeys.includes(key))return tDisplay(v);if(dtKeys.includes(key))return tDisplay(v,units.T,true);return v;}
function fieldInternal(key,v){if(pKeys.includes(key))return pInternal(v);if(dpKeys.includes(key))return pInternal(v,units.p,true);if(tKeys.includes(key))return tInternal(v);if(dtKeys.includes(key))return tInternal(v,units.T,true);return v;}
function fillForm(config){for(const key of Object.keys(engine.defaults)){const el=$(key);if(!el)continue;el.value=typeof config[key]==='number'?Number(fieldDisplay(key,config[key]).toFixed(pKeys.includes(key)||dpKeys.includes(key)?6:4)):config[key];}configureFields();}
function readForm(){const config={};for(const key of Object.keys(engine.defaults)){const el=$(key);if(typeof engine.defaults[key]==='number'){if(!el.value.trim())throw Error('Enter a value for '+el.previousElementSibling.textContent+'.');const number=Number(el.value);if(!Number.isFinite(number))throw Error('Enter a finite numeric value.');config[key]=fieldInternal(key,number);}else config[key]=el.value;}return config;}
function configureFields(){
 $('condensing-field').hidden=$('highMode').value!=='pressure';$('approach-field').hidden=$('highMode').value!=='ambient';
 for(const [name,mode] of [['massFlow','mass'],['load','load'],['displacement','displacement']])$(name+'-field').hidden=$('flowMode').value!==mode;
 const flooded=$('system').value==='flooded';$('evapSH').disabled=flooded;$('system-hint').textContent=flooded?'Ideal separator outlet is dry saturated vapor. No pump or vessel inventory model.':'Dry evaporator outlet with defined superheat.';
 document.querySelectorAll('.punit').forEach(el=>{el.textContent=pLabel();});
 // A pressure drop is a difference, never a gauge reading.
 for(const k of dpKeys)$(k).previousElementSibling.querySelector('.punit').textContent=units.p.startsWith('psi')?'psi':'bar';
 document.querySelectorAll('.tunit').forEach(el=>el.textContent='°'+units.T);document.querySelectorAll('.dunit').forEach(el=>el.textContent=units.T==='C'?'K':'°F Δ');
 $('range-min').textContent=pt(.35);$('range-max').textContent=pt(8);
 const bounds={pressure:[.35,8],condensing:[3,30],ambient:[-20,50],approach:[3,25],evapSH:[0,20],lineSH:[0,20],subcool:[0,20],suctionDrop:[0,.5],liquidDrop:[0,1],etaIs:[40,100],etaMotor:[50,100],massFlow:[.001,5],load:[1,5000],displacement:[1,10000],etaVol:[20,100],evapUA:[.1,1000],condUA:[.1,2000],spaceTemp:[-50,30],dischargeLimit:[80,250],ratioLimit:[2,20]};
 for(const [key,[low,high]] of Object.entries(bounds)){$(key).min=fieldDisplay(key,low);$(key).max=fieldDisplay(key,high);}
}
function invalidateRoom(){roomResult=null;$('export-room').disabled=true;$('room-status').textContent='Operating point changed. Run the room model again.';$('room-chart').innerHTML='<div class="empty">Run the room model for this operating point.</div>';$('room-error').hidden=true;}
function fail(message){result=null;invalidateRoom();$('cycle-error').hidden=false;$('cycle-error').textContent=message;$('draft-status').textContent='No valid operating point is displayed.';$('run-status').textContent='Invalid operating point';$('run-status').classList.add('invalid');$('cycle-svg').classList.add('invalid-graphic');
 for(const id of ['metric-evap','metric-Q','metric-power','metric-COP','metric-discharge','metric-ratio','svg-discharge','svg-liquid-p','svg-liquid-t','svg-mixture','svg-suction-p','svg-suction-t','svg-cycle-temperature'])$(id).textContent='—';
 $('detail-title').textContent='Operating point could not be solved';$('detail-text').textContent=message;$('state-table').innerHTML='';$('ph-chart').innerHTML='<div class="empty">Correct the operating conditions to see a cycle.</div>';$('equipment-values').innerHTML='';$('energy-bars').innerHTML='';$('thermo-checks').innerHTML='';$('hx-checks').innerHTML='';$('point-info').textContent='No solved state.';
 $('diagnostics').innerHTML='<div class="diagnostic bad">'+esc(message)+'</div>';$('diagnostic-summary').textContent='Calculation rejected';enableActions(false);
}
function enableActions(valid){for(const id of ['export-json','export-csv','save-scenario','run-room'])$(id).disabled=!valid;}
function apply(config,announce=true){try{const next=engine.solve(config);applied={...next.config};result=next;fillForm(applied);$('cycle-error').hidden=true;$('draft-status').textContent='All inputs applied.';invalidateRoom();render();if(announce)$('announcement').textContent=`Operating point applied. Cooling duty ${fmt(result.Q)} kW; COP ${fmt(result.COP,2)}.`;return true;}catch(error){fail(error.message);return false;}}
function renderDetail(){
 document.querySelectorAll('[data-step]').forEach(el=>{const active=Number(el.dataset.step)===step;el.classList.toggle('selected',active);el.setAttribute('aria-pressed',String(active));});$('detail-number').textContent=String(step+1).padStart(2,'0');if(!result)return;
 const r=result,[s1,s2,s3,s4,s5]=r.states;
 const details=[['Real-fluid compression',`Vapor enters at ${pt(s1.p)} and ${tt(s1.T)}. The isentropic endpoint is found from constant entropy, then ${applied.etaIs}% compressor efficiency gives an actual discharge of ${tt(s2.T)}. Fluid work is ${fmt(r.W)} kW; motor electrical input is ${fmt(r.electrical)} kW.`],['Condensation & subcooling',`At ${pt(r.pHigh)}, ammonia condenses at ${tt(r.high.T)} and leaves at ${tt(s3.T)}, with ${deltaText(applied.subcool)} subcooling. The condenser rejects ${fmt(r.Qcond)} kW, including suction-line heat and compressor fluid work. External motor losses (${fmt(r.motorLoss)} kW) are separate.`],['Isenthalpic expansion',`The valve lowers liquid pressure to ${pt(r.pEvap)} while enthalpy remains ${fmt(s3.h,2)} kJ/kg. The outlet is at ${tt(s4.T)}, with ${fmt(r.flashFraction*100)}% vapor by mass. Liquid-line pressure loss is checked for flash gas before the valve.`],['Useful evaporation',`${applied.system==='flooded'?'An ideal separator supplies dry saturated vapor to the suction line.':'The evaporator boils the remaining liquid, then provides the specified evaporator superheat.'} Useful cooling is ${fmt(r.Q)} kW at ${pt(r.pEvap)}. Outlet temperature is ${tt(s5.T)}. Suction-line heat (${fmt(r.Qline)} kW) is excluded from useful cooling.`]];
 $('detail-title').textContent=details[step][0];$('detail-text').textContent=details[step][1];
}
function mini(values){return values.map(([label,value])=>'<div>'+esc(label)+'<strong>'+esc(value)+'</strong></div>').join('');}
function render(){if(!result)return;const r=result,[s1,s2,s3,s4]=r.states;enableActions(true);$('run-status').classList.remove('invalid');$('cycle-svg').classList.remove('invalid-graphic');$('graphic').classList.toggle('paused',paused);$('run-status').textContent=paused?'Animation paused':'Operating point solved';$('motion').textContent=paused?'Resume animation':'Pause animation';$('motion').setAttribute('aria-pressed',String(paused));
 $('metric-evap').textContent=tt(r.low.T);$('metric-Q').textContent=fmt(r.Q)+' kW';$('metric-power').textContent=fmt(r.electrical)+' kW';$('metric-COP').textContent=fmt(r.COP,2);$('metric-discharge').textContent=tt(s2.T);$('metric-ratio').textContent=fmt(r.ratio,2)+':1';$('cooling-label').textContent=applied.flowMode==='load'?'Required cooling duty':'Cycle cooling duty';
 $('pressure-slider').value=applied.pressure;$('pressure-slider').setAttribute('aria-valuetext',pt(applied.pressure));$('pressure-equivalent').textContent='Applied: '+pt(applied.pressure)+' · absolute '+fmt(pDisplay(applied.pressure,units.p.startsWith('psi')?'psia':'bara'),units.p.startsWith('psi')?2:3)+' '+(units.p.startsWith('psi')?'psia':'bar(a)');
 $('schematic-title').textContent=applied.system==='flooded'?'Single-stage flooded cycle · ideal separator':'Single-stage direct-expansion cycle';$('separator-symbol').hidden=applied.system!=='flooded';$('separator-symbol').style.display=applied.system==='flooded'?'':'none';
 $('svg-discharge').textContent=pt(s2.p)+' · '+tt(s2.T);$('svg-liquid-p').textContent=pt(s3.p);$('svg-liquid-t').textContent=tt(s3.T)+(applied.subcool>0?' · subcooled':' · saturated');$('svg-mixture').textContent=pt(s4.p)+' · '+tt(s4.T);$('svg-suction-p').textContent=pt(s1.p);$('svg-suction-t').textContent=tt(s1.T)+' · dry vapor';$('svg-cycle-temperature').textContent='Evaporates '+tt(r.low.T)+' → condenses '+tt(r.high.T);
 renderDetail();
 const status=[...r.diagnostics];if(!status.length)$('diagnostics').innerHTML='<div class="diagnostic good">Energy balance closes; dry compression and supported phase boundaries passed. The operating point also passes the user-set screening checks.</div>';else $('diagnostics').innerHTML=status.map(d=>'<div class="diagnostic">'+esc(d.text.replace(/(-?\d+(?:\.\d+)?) °C/g,(_,value)=>tt(Number(value))))+'</div>').join('');$('diagnostic-summary').textContent=status.length?status.length+' screening note'+(status.length>1?'s':''):'Checks passed';
 $('equipment-values').innerHTML=mini([['Refrigerant mass flow',fmt(r.m,4)+' kg/s'],['Required swept volume',fmt(r.requiredDisplacement)+' m³/h'],['Suction vapor density',fmt(s1.rho,3)+' kg/m³'],['Valve flash fraction',fmt(r.flashFraction*100)+'% by mass']]);
 const energy=[['Useful cooling',r.Q,'var(--blue)'],['Suction-line heat',r.Qline,'#87b8c6'],['Fluid work',r.W,'var(--teal)'],['Condenser rejection',r.Qcond,'var(--orange)'],['External motor loss',r.motorLoss,'#a7aba3']];$('energy-bars').innerHTML=energy.map(([name,value,color])=>'<div class="energy-row"><span>'+esc(name)+'</span><div class="energy-track"><div class="energy-bar" style="width:'+fmt(value/r.Qcond*100,4)+'%;background:'+color+'"></div></div><span>'+fmt(value,2)+'</span></div>').join('');
 $('state-table').innerHTML=r.states.map(s=>'<tr><td>'+esc(s.name)+'</td><td>'+esc(pt(s.p))+'</td><td>'+esc(tt(s.T))+'</td><td>'+fmt(s.h,3)+'</td><td>'+fmt(s.s,5)+'</td><td>'+fmt(s.rho,4)+'</td><td>'+(s.x===null?'—':fmt(s.x*100,2)+'%')+'</td><td>'+esc(s.phase)+'</td></tr>').join('');
 $('thermo-checks').innerHTML=mini([['Energy residual',r.balance.toExponential(2)+' kW'],['Carnot COP bound',fmt(r.carnot,2)],['Specific refrigeration',fmt(r.q,2)+' kJ/kg'],['Specific compressor work',fmt(r.w,2)+' kJ/kg'],['Compressor entropy rise',fmt(s2.s-s1.s,5)+' kJ/(kg K)'],['Suction superheat',deltaText(s1.T-engine.sat(s1.p).T)]]);
 $('hx-checks').innerHTML='<p>Evaporator isothermal screening capacity: <strong>'+fmt(r.capacityUA)+' kW</strong>, from UA × (space temperature − evaporation temperature). The cycle duty is '+fmt(r.Q)+' kW.</p><p>Condenser required screening UA: <strong>'+fmt(r.condenserScreenUA,2)+' kW/K</strong>; supplied UA: '+fmt(applied.condUA,2)+' kW/K.</p><p>These estimates omit the separate superheat, desuperheat and subcooling zones. They screen the chosen operating point; they do not solve equipment pressure or guaranteed available capacity.</p>';
 drawPH();
}
function drawPH(){if(!result)return;const r=result,W=900,H=390,left=70,right=35,top=22,bottom=49;const maxH=Math.ceil(Math.max(2000,...r.states.map(s=>s.h))/200)*200,minH=-100;const x=h=>left+(h-minH)/(maxH-minH)*(W-left-right),y=p=>top+(Math.log(35)-Math.log(p))/(Math.log(35)-Math.log(.3))*(H-top-bottom);
 let svg=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Pressure enthalpy chart showing the saturation dome and calculated cycle"><defs><marker id="ph-arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="4" markerHeight="4" orient="auto"><path d="M0 0L10 5L0 10Z" fill="#28796f"/></marker></defs>`;
 for(const p of [.3,.5,1,2,5,10,20,35])svg+=`<path d="M${left} ${y(p)}H${W-right}" stroke="#e0e7e3"/><text x="${left-10}" y="${y(p)+4}" text-anchor="end" fill="#657b83" font-size="10">${esc(fmt(pDisplay(p),units.p.startsWith('psi')?1:2))}</text>`;
 for(let h=0;h<=maxH;h+=400)svg+=`<path d="M${x(h)} ${top}V${H-bottom}" stroke="#e9eeea"/><text x="${x(h)}" y="${H-bottom+20}" text-anchor="middle" fill="#657b83" font-size="10">${h}</text>`;
 const satPoints=data.p.map((p,i)=>({p,hf:data.sat[i][1],hg:data.sat[i][4]}));const dome=satPoints.map(a=>`${x(a.hf)},${y(a.p)}`).join(' ')+' '+[...satPoints].reverse().map(a=>`${x(a.hg)},${y(a.p)}`).join(' ');svg+=`<polygon points="${dome}" fill="#edf3f0" stroke="#bbd1c9" stroke-width="1.5"/><text x="${x(650)}" y="${y(1.5)}" fill="#8a9e95" font-size="11">Liquid + vapor</text>`;
 const [s1,s2,s3,s4,s5,s2s]=r.states;
 const path=points=>points.map((s,i)=>(i?'L':'M')+x(s.h)+' '+y(s.p)).join(' ');
 let compression=[s1],idealCurve=[s1];for(let i=1;i<=30;i++){const p=s1.p*Math.exp(Math.log(s2.p/s1.p)*i/30);const ideal=engine.ps(p,s1.s);idealCurve.push(ideal);compression.push({p,h:s1.h+(ideal.h-s1.h)/(applied.etaIs/100)});}
 const condSat=engine.sat(s2.p);svg+=`<path d="${path(compression)}" stroke="#28796f" stroke-width="3" fill="none" marker-end="url(#ph-arrow)"/><path d="${path(idealCurve)}" stroke="#8ba599" stroke-dasharray="5 4" stroke-width="1.5" fill="none"/><path d="${path([s2,{p:s2.p,h:condSat.hg},{p:s3.p,h:condSat.hf},s3])}" stroke="#dc713e" stroke-width="3" fill="none"/><path d="${path([s3,s4])}" stroke="#7d9990" stroke-width="2.5" fill="none"/><path d="${path([s4,s5,s1])}" stroke="#3389ac" stroke-width="3" fill="none"/>`;
 r.states.forEach((s,i)=>{svg+=`<g tabindex="0" role="button" data-point="${i}" aria-label="Inspect ${esc(s.name)}" style="cursor:pointer"><circle cx="${x(s.h)}" cy="${y(s.p)}" r="12" fill="transparent" pointer-events="all"/><circle cx="${x(s.h)}" cy="${y(s.p)}" r="${i===5?4:6}" fill="${i===5?'#8ba599':'#fff'}" stroke="#28796f" stroke-width="2"/><text x="${x(s.h)+9}" y="${y(s.p)+(i===0?17:-9)}" font-size="11" fill="#17343e">${i===5?'2s':i+1}</text></g>`;});
 svg+=`<text x="${(W+left-right)/2}" y="${H-7}" text-anchor="middle" fill="#657b83" font-size="10">Specific enthalpy · kJ/kg</text><text transform="translate(14 ${H/2}) rotate(-90)" text-anchor="middle" fill="#657b83" font-size="10">Pressure · ${esc(pLabel())} (log absolute spacing)</text></svg>`;
 $('ph-chart').innerHTML=svg;for(const el of $('ph-chart').querySelectorAll('[data-point]')){const select=()=>{const s=r.states[Number(el.dataset.point)];$('point-info').textContent=`${s.name}: ${pt(s.p)}, ${tt(s.T)}, h = ${fmt(s.h,3)} kJ/kg, s = ${fmt(s.s,5)} kJ/(kg K), ${s.phase}.`;};el.addEventListener('click',select);el.addEventListener('keydown',ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();select();}});}
}
function switchTab(name){for(const button of document.querySelectorAll('[data-tab]')){const selected=button.dataset.tab===name;button.setAttribute('aria-selected',String(selected));button.tabIndex=selected?0:-1;$('view-'+button.dataset.tab).hidden=!selected;}}
for(const tab of document.querySelectorAll('[data-tab]')){tab.addEventListener('click',()=>switchTab(tab.dataset.tab));tab.addEventListener('keydown',event=>{const all=[...document.querySelectorAll('[data-tab]')],index=all.indexOf(tab);let next;if(event.key==='ArrowRight')next=(index+1)%all.length;else if(event.key==='ArrowLeft')next=(index+all.length-1)%all.length;else if(event.key==='Home')next=0;else if(event.key==='End')next=all.length-1;if(next!==undefined){event.preventDefault();all[next].focus();switchTab(all[next].dataset.tab);}});}
$('cycle-form').addEventListener('submit',event=>{event.preventDefault();try{apply(readForm());}catch(error){fail(error.message);}});
for(const el of document.querySelectorAll('[data-key]')){el.addEventListener('input',()=>{$('draft-status').textContent='Draft changes — press Apply or Enter.';});el.addEventListener('change',()=>{if(el.id==='system'){$('evapSH').value=el.value==='flooded'?'0':fieldDisplay('evapSH',5);}configureFields();});}
$('pressure-slider').addEventListener('input',()=>{const p=Number($('pressure-slider').value);$('pressure').value=fieldDisplay('pressure',p).toFixed(6);try{apply(readForm(),false);}catch(error){fail(error.message);}});$('pressure-slider').addEventListener('change',()=>{if(result)$('announcement').textContent='Suction pressure applied: '+pt(applied.pressure);});
function changeUnits(next){const oldTemperature=units.T;const roomDraft={};for(const [id,difference] of [['room-initial',false],['room-target',false],['room-deadband',true]]){const raw=$(id).value.trim();roomDraft[id]=raw?tInternal(Number(raw),oldTemperature,difference):null;}const draft={};for(const key of allNumeric){const v=Number($(key).value);draft[key]=$(key).value.trim()?fieldInternal(key,v):null;}units=next;for(const [id,difference] of [['room-initial',false],['room-target',false],['room-deadband',true]])if(roomDraft[id]!==null)$(id).value=Number(tDisplay(roomDraft[id],units.T,difference).toFixed(6));for(const key of allNumeric)if(draft[key]!==null)$(key).value=Number(fieldDisplay(key,draft[key]).toFixed(6));configureFields();if(result)render();else $('range-min').textContent=pt(.35);renderScenarios();if(roomResult){renderRoomStatus();drawRoom(roomResult.inputs);}}
$('pressure-unit').addEventListener('change',()=>changeUnits({...units,p:$('pressure-unit').value}));$('temperature-unit').addEventListener('change',()=>changeUnits({...units,T:$('temperature-unit').value}));
$('reset').addEventListener('click',()=>{changeUnits({...DEFAULT_UNITS});$('pressure-unit').value=DEFAULT_UNITS.p;$('temperature-unit').value=DEFAULT_UNITS.T;paused=false;step=0;apply({...engine.defaults});});
const presets={storage:{...engine.defaults,pressure:engine.satP(-20),spaceTemp:-10,ambient:25,highMode:'ambient',approach:10,flowMode:'load',load:100,evapUA:15,condUA:30},freezer:{...engine.defaults,system:'flooded',pressure:engine.satP(-35),evapSH:0,lineSH:5,ambient:20,condensing:10,spaceTemp:-25,flowMode:'mass',massFlow:.05,evapUA:10,condUA:30},chiller:{...engine.defaults,pressure:engine.satP(-5),spaceTemp:5,ambient:30,highMode:'ambient',approach:10,flowMode:'displacement',displacement:120,etaVol:75,evapUA:20,condUA:40}};
for(const button of document.querySelectorAll('[data-preset]'))button.addEventListener('click',()=>apply(presets[button.dataset.preset]));
for(const el of document.querySelectorAll('[data-step]')){const choose=()=>{step=Number(el.dataset.step);renderDetail();};el.addEventListener('click',choose);if(el.tagName.toLowerCase()==='g')el.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();choose();}});}
$('motion').addEventListener('click',()=>{paused=!paused;$('graphic').classList.toggle('paused',paused);$('motion').textContent=paused?'Resume animation':'Pause animation';$('motion').setAttribute('aria-pressed',String(paused));if(result)$('run-status').textContent=paused?'Animation paused':'Operating point solved';});$('print').addEventListener('click',()=>window.print());
function download(name,text,type){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function csv(rows){return rows.map(row=>row.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\r\n');}
function exportObject(){return {schema:'ammonia-lab-scenario',schemaVersion:1,solverVersion:'0.2.0',name:$('scenario-name').value.trim()||'Ammonia operating point',createdAt:new Date().toISOString(),propertyEngine:data.version,config:applied,results:result,validation};}
$('export-json').addEventListener('click',()=>{if(result)download('ammonia-scenario-v020.json',JSON.stringify(exportObject(),null,2),'application/json');});
$('export-csv').addEventListener('click',()=>{if(!result)return;const r=result;const rows=[['Ammonia Lab','0.2.0',data.version],['State','Pressure bar absolute','Temperature C','Enthalpy kJ/kg','Entropy kJ/(kg K)','Density kg/m3','Vapor mass fraction','Phase'],...r.states.map(s=>[s.name,s.p,s.T,s.h,s.s,s.rho,s.x===null?'':s.x,s.phase]),[],['Output','Value','Unit'],['Useful cooling',r.Q,'kW'],['Electrical input',r.electrical,'kW'],['COP',r.COP,'kW/kW'],['Fluid work',r.W,'kW'],['Suction-line heating',r.Qline,'kW'],['Condenser rejection',r.Qcond,'kW'],['Motor losses',r.motorLoss,'kW'],['Mass flow',r.m,'kg/s'],['Energy residual',r.balance,'kW'],[],['Input','Value','SI / mode'],...Object.entries(applied).map(([k,v])=>[k,v,'']),[],['Diagnostic'],...r.diagnostics.map(d=>[d.text])];download('ammonia-results-v020.csv',csv(rows),'text/csv');});
function normalizeConfig(config){if(!config||typeof config!=='object'||Array.isArray(config))throw Error('Scenario config must be an object.');const clean={};for(const key of Object.keys(engine.defaults)){if(!(key in config))throw Error('Missing scenario input: '+key);if(typeof config[key]!==typeof engine.defaults[key])throw Error('Incorrect input type: '+key);clean[key]=config[key];}engine.solve(clean);return clean;}
function persist(){try{localStorage.setItem(STORAGE,JSON.stringify(scenarios));return true;}catch(error){$('scenario-status').textContent='Browser storage is unavailable. Scenarios remain in this session; export JSON to keep them.';return false;}}
function addScenario(name,config){if(scenarios.length>=20)throw Error('The scenario limit is 20. Delete one before saving another.');const clean=normalizeConfig(config);scenarios.push({id:Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8),name:String(name).slice(0,80),createdAt:new Date().toISOString(),config:clean});const stored=persist();renderScenarios();if(stored)$('scenario-status').textContent='Scenario saved in this browser.';}
function renderScenarios(){if(!scenarios.length)$('scenario-list').innerHTML='<div class="empty">No saved scenarios yet.</div>';else $('scenario-list').innerHTML=scenarios.map(s=>`<div class="scenario-item"><div><div class="scenario-name">${esc(s.name)}</div><div class="scenario-meta">${esc(s.config.system==='dx'?'Direct expansion':'Ideal flooded')} · suction ${esc(pt(s.config.pressure))}<br>${esc(new Date(s.createdAt).toLocaleString())}</div></div><div class="scenario-buttons"><label><input type="checkbox" data-compare="${esc(s.id)}" ${compared.has(s.id)?'checked':''}> Compare</label><button class="btn" data-restore="${esc(s.id)}">Restore</button><button class="btn" data-delete="${esc(s.id)}">Delete</button></div></div>`).join('');
 for(const b of document.querySelectorAll('[data-restore]'))b.addEventListener('click',()=>{const s=scenarios.find(x=>x.id===b.dataset.restore);apply(s.config);$('scenario-status').textContent='Restored '+s.name+'.';});
 for(const b of document.querySelectorAll('[data-delete]'))b.addEventListener('click',()=>{scenarios=scenarios.filter(x=>x.id!==b.dataset.delete);compared.delete(b.dataset.delete);persist();renderScenarios();renderComparison();});
 for(const box of document.querySelectorAll('[data-compare]'))box.addEventListener('change',()=>{if(box.checked&&compared.size>=4){box.checked=false;$('scenario-status').textContent='Compare up to four scenarios.';return;}box.checked?compared.add(box.dataset.compare):compared.delete(box.dataset.compare);renderComparison();});renderComparison();
}
function renderComparison(){const selected=scenarios.filter(s=>compared.has(s.id));if(!selected.length){$('comparison').innerHTML='<div class="empty">Select Compare next to a saved scenario.</div>';return;}const evaluated=selected.map(s=>({scenario:s,result:engine.solve(s.config)}));const fields=[['Evaporating temperature',r=>tt(r.low.T)],['Cooling duty',r=>fmt(r.Q)+' kW'],['Electrical input',r=>fmt(r.electrical)+' kW'],['COP',r=>fmt(r.COP,3)],['Discharge temperature',r=>tt(r.states[1].T)],['Mass flow',r=>fmt(r.m,4)+' kg/s'],['Compression ratio',r=>fmt(r.ratio,2)+':1'],['Screening notes',r=>String(r.diagnostics.length)]];$('comparison').innerHTML='<table><thead><tr><th>Quantity</th>'+evaluated.map(e=>'<th>'+esc(e.scenario.name)+'</th>').join('')+'</tr></thead><tbody>'+fields.map(([label,get])=>'<tr><td>'+esc(label)+'</td>'+evaluated.map(e=>'<td>'+esc(get(e.result))+'</td>').join('')+'</tr>').join('')+'</tbody></table>';}
$('save-scenario').addEventListener('click',()=>{if(!result)return;try{addScenario($('scenario-name').value.trim()||'Operating point '+(scenarios.length+1),applied);}catch(error){$('scenario-status').textContent=error.message;}});$('import-trigger').addEventListener('click',()=>$('import-file').click());
$('import-file').addEventListener('change',async()=>{const file=$('import-file').files[0];if(!file)return;try{if(file.size>1000000)throw Error('Scenario file is too large.');const obj=JSON.parse(await file.text());if(obj.schema!=='ammonia-lab-scenario'||obj.schemaVersion!==1||obj.solverVersion!=='0.2.0')throw Error('Import requires an Ammonia Lab v0.2.0 scenario export.');addScenario(typeof obj.name==='string'?obj.name:'Imported point',obj.config);}catch(error){$('scenario-status').textContent='Import rejected: '+error.message;}finally{$('import-file').value='';}});
$('room-form').addEventListener('submit',event=>{event.preventDefault();roomResult=null;$('export-room').disabled=true;try{if(!result)throw Error('Apply a valid cycle first.');if(result.diagnostics.some(d=>d.code==='cond-ua'))throw Error('Resolve the condenser UA screening failure before running the room model.');const ids={initial:'room-initial',target:'room-target',deadband:'room-deadband',thermalMass:'room-mass',leakUA:'room-leak',internalGain:'room-gain',hours:'room-hours'},opts={};for(const [key,id] of Object.entries(ids)){if(!$(id).value.trim())throw Error('Fill in every room-model input.');opts[key]=Number($(id).value);if(key==='initial'||key==='target')opts[key]=tInternal(opts[key]);else if(key==='deadband')opts[key]=tInternal(opts[key],units.T,true);}if(opts.initial< -50||opts.initial>50||opts.target< -50||opts.target>30||opts.thermalMass<.1||opts.thermalMass>100000||opts.leakUA>100||opts.internalGain>5000||opts.deadband>20)throw Error('Room inputs exceed the supported screening range.');roomResult=engine.roomSimulation(result,opts);roomResult.inputs=opts;$('room-error').hidden=true;renderRoomStatus();$('export-room').disabled=false;drawRoom(opts);}catch(error){$('room-error').hidden=false;$('room-error').textContent=error.message;$('room-status').textContent='No valid room simulation is displayed.';$('room-chart').innerHTML='<div class="empty">Correct the room inputs, then run again.</div>';}});
function renderRoomStatus(){$('room-status').textContent=(roomResult.firstSetpoint===null?'Setpoint was not reached in the simulated duration.':'First reached setpoint after '+fmt(roomResult.firstSetpoint)+' minutes.')+' Final room: '+tt(roomResult.finalT)+'; compressor electricity: '+fmt(roomResult.energy)+' kWh. Changes to cycle inputs require a new run.';}
function drawRoom(opts){const rows=roomResult.rows,W=900,H=330,l=58,rr=22,t=22,b=43,maxT=Math.ceil(Math.max(opts.initial,...rows.map(r=>r.T))+2),minT=Math.floor(Math.min(opts.target-opts.deadband,...rows.map(r=>r.T))-2);const x=min=>l+min/(opts.hours*60)*(W-l-rr),y=T=>t+(maxT-T)/(maxT-minT)*(H-t-b);let svg=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Room temperature versus time, thermostat band and compressor activity"><rect x="${l}" y="${y(opts.target+opts.deadband/2)}" width="${W-l-rr}" height="${y(opts.target-opts.deadband/2)-y(opts.target+opts.deadband/2)}" fill="#e5efe5"/>`;
 for(let i=0;i<=5;i++){const T=minT+(maxT-minT)*i/5;svg+=`<path d="M${l} ${y(T)}H${W-rr}" stroke="#e1e8e2"/><text x="${l-9}" y="${y(T)+4}" text-anchor="end" font-size="10" fill="#657b83">${fmt(tDisplay(T))}</text>`;const hour=opts.hours*i/5;svg+=`<text x="${x(hour*60)}" y="${H-b+19}" text-anchor="middle" font-size="10" fill="#657b83">${fmt(hour)}</text>`;}
 const path=rows.map((r,i)=>(i?'L':'M')+x(r.minutes)+' '+y(r.T)).join(' ');svg+=`<path d="${path}" stroke="#3389ac" stroke-width="2.5" fill="none"/>`;
 for(let i=0;i<rows.length-1;i++)if(rows[i].on)svg+=`<rect x="${x(rows[i].minutes)}" y="${H-b-5}" width="${Math.max(.5,x(rows[i+1].minutes)-x(rows[i].minutes))}" height="5" fill="#28796f"/>`;
 svg+=`<text x="${W/2}" y="${H-7}" text-anchor="middle" fill="#657b83" font-size="10">Time · hours (green strip: compressor enabled)</text><text transform="translate(14 ${H/2}) rotate(-90)" text-anchor="middle" fill="#657b83" font-size="10">Room temperature · °${units.T}</text></svg>`;$('room-chart').innerHTML=svg;
}
$('export-room').addEventListener('click',()=>{if(!roomResult)return;download('ammonia-room-timeseries.csv',csv([['Minutes','Room C','Compressor enabled','Cumulative compressor kWh'],...roomResult.rows.map(r=>[r.minutes,r.T,r.on,r.electricalKWh])]),'text/csv');});
function renderValidation(){const c=validation.counts,e=validation.maxErrors;$('validation-grid').innerHTML=`<div><strong>${c.singlePhaseStates+c.saturationStates}</strong><span>Property reference states</span></div><div><strong>${c.cycles}</strong><span>Full-cycle comparisons</span></div><div><strong>${c.manufacturerCorrelationPoints}</strong><span>Manufacturer fit checks</span></div>`;const rows=[['Saturation temperature vs direct CoolProp',fmt(e.temperatureK,6)+' K'],['Specific enthalpy vs direct CoolProp',fmt(e.enthalpyPercent,5)+'%'],['Density vs direct CoolProp',fmt(e.densityPercent,5)+'%'],['Cycle discharge temperature',fmt(e.dischargeK,5)+' K'],['Cycle cooling duty',fmt(e.cycleCoolingPercent,5)+'%'],['Cycle electrical input',fmt(e.cycleElectricalPercent,5)+'%'],['Cycle COP',fmt(e.cycleCOPPercent,5)+'%'],['Cycle energy residual',e.energyResidualKW.toExponential(2)+' kW'],['Danfoss pressure–temperature fit agreement',fmt(e.manufacturerFitK,3)+' K'],['Out-of-domain cycle cases rejected',String(c.outOfDomainCyclesRejected)]];$('validation-table').innerHTML=rows.map(([label,value])=>'<tr><td>'+esc(label)+'</td><td>'+esc(value)+'</td></tr>').join('');}
try{const stored=JSON.parse(localStorage.getItem(STORAGE)||'[]');if(Array.isArray(stored)){for(const s of stored.slice(0,20)){try{if(typeof s.id!=='string'||typeof s.name!=='string'||!Number.isFinite(Date.parse(s.createdAt)))continue;scenarios.push({id:s.id.slice(0,80),name:s.name.slice(0,80),createdAt:s.createdAt,config:normalizeConfig(s.config)});}catch{}}}}catch{$('scenario-status').textContent='Browser storage is unavailable; use JSON exports to keep scenarios.';}
$('pressure-unit').value=DEFAULT_UNITS.p;$('temperature-unit').value=DEFAULT_UNITS.T;fillForm(applied);renderValidation();renderScenarios();apply(applied,false);if(window.AmmoniaStartup)window.AmmoniaStartup.ready=true;$('startup-notice').hidden=true;
})();
