'use strict';
(()=>{
 const $=id=>document.getElementById(id),esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const engine=AmmoniaEngine.createEngine(JSON.parse($('property-data').textContent)),model=AmmoniaStorage.createStorage(engine,AmmoniaProfiles);
 const schematic=AmmoniaSchematic.create($('storage-schematic'));
 const trends=AmmoniaTrends.create($('storage-trends'));
 let state=null,running=false,timer=null,last=0,units={p:'psig',T:'F'},training=null,observedFault=null;
 const f=(v,n=3)=>Number.isFinite(v)?v.toFixed(n):'—',temp=v=>Number.isFinite(v)?(units.T==='F'?v*1.8+32:v):NaN;
 const pressure=v=>Number.isFinite(v)?(v-(units.p.endsWith('g')?1.01325:0))*(units.p.startsWith('psi')?14.503773773:1):NaN,pl=()=>({bara:'bar(a)',barg:'bar(g)',psia:'psia',psig:'psig'})[units.p];
 function operations(){const o={thermalMode:$('storage-thermalMode').value,compressorOn:$('storage-compressorOn').checked,circuit:$('storage-circuit').value,valveMode:$('storage-valveMode').value,drainEnabled:$('storage-drainEnabled').checked};for(const key of ['receiverHeat','evaporatorHeat','condenserHeat']){if(!$('storage-'+key).value.trim())throw Error('Fill in storage heat rates.');o[key]=Number($('storage-'+key).value);}if(!$('storage-compressorSpeed').value.trim())throw Error('Fill in compressor speed.');o.speed=Number($('storage-compressorSpeed').value)/100;for(const key of ['manualOpening','superheatTarget','kp','ki']){const el=$('storage-'+key);if(!el.value.trim())throw Error('Fill in valve operating controls.');o[key]=Number(el.value);}o.manualOpening/=100;o.superheatTarget/=units.T==='F'?1.8:1;if($('storage-capacity-mode').value!=='legacy')o.compressorDemand=$('storage-compressorDemand').checked;return model.validateOperations(o);}
 const capacityKeys=['suctionTarget','minSpeed','maxSpeed','deadbandBar','kp','ki','sensorSeconds','actuatorSeconds','rampPerSecond','trackingSeconds','startDelay','minOn','minOff'];
 const capacityId=k=>'storage-capacity-'+(k==='suctionTarget'?'target':k);
 const fromPressure=v=>v/(units.p.startsWith('psi')?14.503773773:1)+(units.p.endsWith('g')?1.01325:0);
 function capacitySettings(){
  const mode=$('storage-capacity-mode').value;if(mode==='legacy')return null;
  const c={mode};for(const k of capacityKeys){const el=$(capacityId(k));if(!el.value.trim())throw Error('Fill in compressor capacity settings.');c[k]=Number(el.value);}
  c.suctionTarget=readPressureDraft('suctionTarget');c.minSpeed/=100;c.maxSpeed/=100;c.deadbandBar=readPressureDraft('deadbandBar');if(state?.capacity)for(const k of capacityKeys)if(Math.abs(c[k]-state.capacity.settings[k])<1e-12)c[k]=state.capacity.settings[k];return c;
 }
 function applyControls(){
  const c=capacitySettings();if(!!state.capacity!==!!c)throw Error('Initialize/reset the circuit to switch between legacy and managed capacity.');
  model.update(state,operations(),roomBoundary(),c);
  if(state.capacity&&state.capacity.settings.mode==='manual')$('storage-compressorSpeed').value=state.capacity.settings.manualSpeed*100;
 }
 function writePressureDraft(k,si){const el=$(capacityId(k)),v=k==='suctionTarget'?pressure(si):si*(units.p.startsWith('psi')?14.503773773:1);el.value=Number(v.toFixed(6));el.dataset.display=el.value;el.dataset.si=si;el.dataset.unit=units.p;}
 function readPressureDraft(k){const el=$(capacityId(k));if(el.value===el.dataset.display&&el.dataset.unit===units.p)return Number(el.dataset.si);return k==='suctionTarget'?fromPressure(Number(el.value)):Number(el.value)/(units.p.startsWith('psi')?14.503773773:1);}
 function fillCapacity(c=AmmoniaCapacity.DEFAULTS){
  for(const k of capacityKeys){if(['suctionTarget','deadbandBar'].includes(k)){writePressureDraft(k,c[k]);continue;}$(capacityId(k)).value=['minSpeed','maxSpeed'].includes(k)?c[k]*100:c[k];}
 }
 function capacityAvailability(){const legacy=$('storage-capacity-mode').value==='legacy';for(const k of capacityKeys)$(capacityId(k)).disabled=legacy;$('storage-compressorDemand').disabled=legacy;capacityDraft();document.querySelector('label[for="storage-compressorSpeed"]').textContent=$('storage-capacity-mode').value==='auto'?'Manual speed request · % (automatic computes output)':'Manual compressor speed request · %';}
 function capacityDraft(){
  const draft=$('storage-capacity-mode').value,managed=draft!=='legacy',applied=state?.capacity?.settings.mode||'legacy';
  let text=!state?'Initialize/reset applies these settings to a new run.':managed!==!!state.capacity?'Reset required: this mode changes the controller basis and replaces the current run.':'Readings show applied settings. Apply operating controls, Start or Advance commits the form inputs.';
  if(state&&managed===!!state.capacity&&draft!==applied)text='Mode change pending: '+draft+' will apply with operating controls; current readings remain '+applied+'.';
  if(state?.capacity?.running&&managed){const actual=state.capacity.speed*100,low=Number($('storage-capacity-minSpeed').value),high=Number($('storage-capacity-maxSpeed').value);if(actual<low||actual>high)text+=' Stop first: these limits exclude actual speed ('+f(actual,1)+'%). Disable and Apply with the existing limits, then edit the range.';}
  $('storage-capacity-draft').textContent=text;
 }
 function capacityPresentation(r,comp){
  const c=r.capacity,on=!r.fault&&!comp.inhibited&&(c?c.running:r.operations.compressorOn),actual=c?c.actualSpeed:(on?r.operations.speed:0);
  const values=[['Compressor mode',c?(c.mode==='auto'?'Automatic suction PI':'Managed manual'):'Legacy manual'],['Suction pressure',f(pressure((r.vessels.outlet||r.vessels.evaporator).p),2)+' '+pl()],['Applied suction target',c?f(pressure(c.targetBarAbsolute),2)+' '+pl():'Not controlled in legacy mode'],['Requested / actual speed',f((c?.requestedSpeed??(on?r.operations.speed:0))*100,1)+' / '+f(actual*100,1)+' %'],['Compressor state',r.fault?'STOPPED':comp.inhibited?'UNAVAILABLE':on?'ON':'OFF'],['Applied run demand',c?(r.operations.compressorDemand?'Requested':'Not requested'):'Manual enable only'],['Playback',running?'Running':'Paused']];
  $('storage-capacity-readings').innerHTML=values.map(([k,v])=>'<div><span>'+esc(k)+'</span><strong>'+esc(v)+'</strong></div>').join('');
  const timers=c?[[c.minimumOffRemaining,'minimum rest'],[c.minimumOnRemaining,'minimum run'],[c.startDelayRemaining,'start delay']].filter(([n])=>n>1e-8).map(([n,label])=>label+' '+f(n,1)+' s remaining'):[];
  $('storage-capacity-note').textContent=r.fault?r.fault.message:c?c.reason+(c.limitedBy.length?' · Limited by '+c.limitedBy.join(', '):'')+(timers.length?' · '+timers.join(' · '):''):'Legacy manual speed has no managed lag or start/rest timers. Feed control: '+r.operations.valveMode+'.';
 }
 function roomBoundary(){const c={};for(const key of ['ambient','gain','leakUA']){const el=$('storage-'+key);if(!el.value.trim())throw Error('Fill in room/condenser boundaries.');c[key]=Number(el.value);}if(units.T==='F')c.ambient=(c.ambient-32)/1.8;return c;}
 function showError(e){$('storage-error').textContent=e.message;$('storage-error').hidden=false;}
 function clearError(){$('storage-error').hidden=true;}
 function pause(reason='User pause'){if(running&&state)model.logPlayback(state,'pause',{reason});running=false;clearInterval(timer);timer=null;$('storage-pause').disabled=true;render();}
 function initialize(){const snapshot=AmmoniaPlantSnapshot(),next=model.create(snapshot.profile,{...snapshot.roomConfig,...roomBoundary()},operations(),capacitySettings());training?.interrupt('Connected run reinitialized outside the exercise.');pause();state=next;clearError();render();}
 function step(seconds){if(!state)initialize();model.advance(state,seconds,[],training?.isActive()?training.acceptBoundary:null);if(state.fault)pause('Simulation stop');render();}
 function render(){
  capacityAvailability();
  for(const option of $('storage-capacity-mode').options)option.disabled=option.value!=='legacy'&&AmmoniaPlantSnapshot().profile.equipment.compressors!==1;
  $('storage-start').disabled=running;$('storage-export').disabled=!state;
  training?.update(state);
  if(!state){schematic.update(null,units,false);trends.update(null,units);$('storage-clock').textContent='0.0 s simulated';$('storage-capacity-readings').innerHTML='';$('storage-capacity-note').textContent='Initialize a run to see applied capacity and compressor status.';$('storage-metrics').innerHTML='';$('storage-states').innerHTML='';$('storage-balance').innerHTML='';$('storage-flows').innerHTML='';$('storage-flow-window').textContent='';return;}
  if(state.fault!==observedFault){observedFault=state.fault;if(observedFault)$('storage-diagnostics').open=true;}
  const r=model.record(state);capacityPresentation(r,model.observeCompressor(state));schematic.update({...r,profileLabel:state.profile.name+' revision '+state.profile.revision,compressor:model.observeCompressor(state)},units,running);$('storage-clock').textContent=f(state.time,1)+' s simulated';
  const status=state.fault?{equipment:'TRIPPED',solver:'SOLVER LIMIT',domain:'MODEL LIMIT'}[state.fault.kind]:running?'Running':'Paused';
  $('storage-status').textContent=status+' · '+state.profile.name+' revision '+state.profile.revision+(state.fault?' · '+state.fault.message+' · detected at '+f(state.fault.seconds,3)+' s. Correct controls and clear the stop, or reinitialize storage.':' · '+state.operations.thermalMode+' boundaries · '+state.operations.circuit+' circuit.');
  if(state.fault?.readings){const v=state.fault.readings;$('storage-status').textContent+=' Captured suction / discharge '+f(pressure(v.pressure),2)+' / '+f(pressure(v.condensing),2)+' '+pl()+', discharge temperature '+f(temp(v.discharge),2)+' °'+units.T+'.';}
  const metrics=[['Stored charge',f(r.totalMassKg)+' kg'],['Room temperature',f(temp(state.T),2)+' °'+units.T],['Compressor electricity',f(r.electricalKWh,5)+' kWh']];$('storage-metrics').innerHTML=metrics.map(([label,value])=>'<div class="metric"><label>'+esc(label)+'</label><strong style="font-size:20px">'+esc(value)+'</strong></div>').join('');
  $('storage-states').innerHTML='<table><thead><tr><th>Volume</th><th>Pressure · '+esc(pl())+'</th><th>Temperature · °'+units.T+'</th><th>Phase</th><th>Mass · kg</th><th>Liquid volume · %</th><th>Vapor mass · %</th><th>Internal energy · kJ</th></tr></thead><tbody>'+Object.entries(r.vessels).map(([key,v])=>'<tr><td>'+key+'</td><td>'+f(pressure(v.p),2)+'</td><td>'+f(temp(v.T),2)+'</td><td>'+esc(v.phase)+'</td><td>'+f(v.massKg)+'</td><td>'+f(v.liquidVolumeFraction*100,2)+'</td><td>'+f(v.x===null?NaN:v.x*100,2)+'</td><td>'+f(v.internalEnergyKJ)+'</td></tr>').join('')+'</tbody></table>';
  const balance=[['Mass residual',f(r.massResidualKg,9)+' kg'],['Combined room / refrigerant energy residual',f(r.energyResidualKJ,7)+' kJ'],['External heat',f(r.externalHeatKJ)+' kJ'],['Mechanical work into refrigerant (compressor + drain head)',f(r.fluidWorkKJ)+' kJ'],['Drain gravity contribution',f(r.gravityEnergyKJ)+' kJ'],['Accepted / rejected integration steps',r.acceptedSteps+' / '+r.rejectedSteps]];$('storage-balance').innerHTML=balance.map(([label,value])=>'<div>'+esc(label)+'<strong>'+esc(value)+'</strong></div>').join('');
  const flows=r.flows;$('storage-flow-window').textContent=flows?.interval?'Port flows averaged over '+f(flows.interval.from,4)+'–'+f(flows.interval.to,4)+' simulated seconds.':'Port flow demand at the current state.';if(flows&&!flows.error){const values=[['Actual outlet superheat',f(flows.superheat*(units.T==='F'?1.8:1),2)+' '+(units.T==='F'?'°F Δ':'K')],['Measured sensor superheat',f(r.controller.sensor*(units.T==='F'?1.8:1),2)+' '+(units.T==='F'?'°F Δ':'K')],['Valve command / actual opening',f(flows.command*100,2)+' / '+f(r.controller.opening*100,2)+' %'],...['feed','drain','vapor'].map(k=>[k+' flow',f(flows[k].massFlow,5)+' kg/s · '+flows[k].status+(flows[k].phaseLimited?' · phase supply limited':'')])];$('storage-flows').innerHTML=values.map(([k,v])=>'<div>'+esc(k)+'<strong>'+esc(v)+'</strong></div>').join('');}else $('storage-flows').textContent=flows?.error||'Feed and drain isolated.';trends.update(state.history,units);
 }
 $('storage-example').addEventListener('click',()=>{try{pause();$('storage-capacity-mode').value='legacy';$('storage-compressorDemand').checked=true;$('storage-circuit').value='circulating';$('storage-thermalMode').value='air';$('storage-compressorOn').checked=true;$('storage-compressorSpeed').value=70;$('storage-valveMode').value='auto';$('storage-drainEnabled').checked=true;for(const [key,value]of Object.entries({receiverHeat:0,evaporatorHeat:0,condenserHeat:0,manualOpening:25,superheatTarget:units.T==='F'?9:5,kp:.04,ki:.004,ambient:units.T==='F'?77:25,gain:2,leakUA:.1}))$('storage-'+key).value=value;initialize();}catch(e){showError(e);}});
 $('storage-initialize').addEventListener('click',()=>{try{initialize();}catch(e){showError(e);}});
 $('storage-step').addEventListener('click',()=>{try{pause();if(state)applyControls();clearError();if(!state)initialize();model.logPlayback(state,'step',{requestedSeconds:10,reason:'Advance requested: 10 simulated seconds'});step(10);}catch(e){showError(e);}});
 $('storage-pause').addEventListener('click',()=>pause());
 $('storage-start').addEventListener('click',()=>{try{if(!state)initialize();if(state.fault)throw Error('Clear the storage stop after correcting controls, or reinitialize.');applyControls();$('live-pause').click();clearError();running=true;model.logPlayback(state,'start',{speed:Number($('storage-speed').value)});$('storage-pause').disabled=false;last=performance.now();timer=setInterval(()=>{try{const now=performance.now(),elapsed=Math.min(1,(now-last)/1000);last=now;step(elapsed*Number($('storage-speed').value));}catch(e){pause();showError(e);}},250);render();}catch(e){showError(e);}});
 $('storage-form').addEventListener('submit',e=>{e.preventDefault();try{if(state)applyControls();else {operations();const c=capacitySettings();if(c)AmmoniaCapacity.normalize(AmmoniaPlantSnapshot().profile,c);}clearError();render();}catch(e){showError(e);}});
 $('storage-clear').addEventListener('click',()=>{if(state){model.clearFault(state);clearError();render();}});
 document.addEventListener('ammonia-equipment',()=>{training?.interrupt('Applied equipment changed.');pause();state=null;if(AmmoniaPlantSnapshot().profile.equipment.compressors!==1)$('storage-capacity-mode').value='legacy';render();$('storage-status').textContent='Active equipment changed. Initialize storage from the new profile.';});
 document.addEventListener('ammonia-run-live',()=>pause('Switched to quasi-steady playback'));
 document.addEventListener('ammonia-units',e=>{const ambient=$('storage-ambient'),air=ambient.value.trim()?(units.T==='F'?(Number(ambient.value)-32)/1.8:Number(ambient.value)):null;const el=$('storage-superheatTarget'),v=el.value.trim()?Number(el.value)/(units.T==='F'?1.8:1):null;const target=$('storage-capacity-target'),deadband=$('storage-capacity-deadbandBar'),targetSI=target.value.trim()?readPressureDraft('suctionTarget'):null,bandSI=deadband.value.trim()?readPressureDraft('deadbandBar'):null;units={...e.detail};if(targetSI!==null)writePressureDraft('suctionTarget',targetSI);if(bandSI!==null)writePressureDraft('deadbandBar',bandSI);document.querySelectorAll('.capacity-punit').forEach(el=>el.textContent=pl());document.querySelectorAll('.capacity-dpunit').forEach(el=>el.textContent=units.p.startsWith('psi')?'psi Δ':'bar Δ');if(air!==null)ambient.value=units.T==='F'?air*1.8+32:air;$('storage-tunit').textContent='°'+units.T;if(v!==null)el.value=v*(units.T==='F'?1.8:1);$('storage-dunit').textContent=units.T==='F'?'°F Δ':'K';render();});
 document.addEventListener('visibilitychange',()=>{if(document.hidden&&running)pause('Browser moved to background');});
 window.addEventListener('error',()=>{if(running)pause('Browser error');});window.addEventListener('unhandledrejection',()=>{if(running)pause('Browser error');});
 $('storage-speed').addEventListener('change',()=>{if(state){model.logPlayback(state,'speed',{speed:Number($('storage-speed').value)});render();}});
 $('storage-export').addEventListener('click',()=>{
  if(!state)return;const rows=[['Storage model','v0.5.5; conservative connected circuit'],['Equipment JSON SI',JSON.stringify(state.profile)],['Initial room conditions JSON SI',JSON.stringify(state.initialRoomConfig)],['Current room conditions JSON SI',JSON.stringify(state.roomConfig)],['Seconds','Room C','Charge kg','Refrigerant U kJ','Room energy change kJ','Mass residual kg','Combined energy residual kJ','External heat kJ','Fluid work kJ','Compressor kWh','Thermal mode','Receiver heat kW','Evaporator heat kW','Condenser heat kW','Compressor enabled','Speed fraction',...Object.keys(state.vessels).flatMap(key=>[key+' bar absolute',key+' C',key+' phase',key+' kg',key+' U kJ',key+' liquid volume fraction',key+' vapor mass fraction']),'Circuit','Valve mode','Manual command fraction','Superheat target K','PI kp fraction/K','PI ki fraction/(K s)','Drain enabled','Actual opening fraction','Sensor superheat K','Integrator fraction','Actual superheat K','Feed kg/s','Drain kg/s','Vapor link kg/s','Flow diagnostics JSON SI','Drain gravity energy kJ','Ambient C','Room gain kW','Room leak UA kW/K','Fault snapshot JSON SI','Fault kind','Fault message','Fault detection seconds','Fault readings JSON SI'],...state.rows.map(r=>[r.seconds,r.T,r.totalMassKg,r.totalEnergyKJ,r.roomEnergyKJ,r.massResidualKg,r.energyResidualKJ,r.externalHeatKJ,r.fluidWorkKJ,r.electricalKWh,r.operations.thermalMode,r.operations.receiverHeat,r.operations.evaporatorHeat,r.operations.condenserHeat,r.operations.compressorOn,r.operations.speed,...Object.values(r.vessels).flatMap(v=>[v.p,v.T,v.phase,v.massKg,v.internalEnergyKJ,v.liquidVolumeFraction,v.x??'']),r.operations.circuit,r.operations.valveMode,r.operations.manualOpening,r.operations.superheatTarget,r.operations.kp,r.operations.ki,r.operations.drainEnabled,r.controller.opening,r.controller.sensor,r.controller.integral,r.flows?.superheat??'',r.flows?.feed?.massFlow??'',r.flows?.drain?.massFlow??'',r.flows?.vapor?.massFlow??'',JSON.stringify(r.flows),r.gravityEnergyKJ,r.roomBoundary.ambient,r.roomBoundary.gain,r.roomBoundary.leakUA,r.fault?JSON.stringify(r.fault):'',r.fault?.kind??'',r.fault?.message??'',r.fault?.seconds??'',r.fault?JSON.stringify(r.fault.readings):''])];
  if(state.capacity){rows[4].push('Compressor run demand');state.rows.forEach((r,i)=>rows[i+5].push(r.operations.compressorDemand));const columns=['Capacity mode','Requested compressor fraction','Actual compressor fraction','Suction target bar absolute','Measured suction bar absolute','Sensed suction bar absolute','Capacity JSON SI'];rows[4].push(...columns);state.rows.forEach((r,i)=>{const c=r.capacity;rows[i+5].push(...(c?[c.mode,c.requestedSpeed,c.actualSpeed,c.targetBarAbsolute,c.measuredPressureBarAbsolute,c.sensedPressureBarAbsolute,JSON.stringify(c)]:Array(columns.length).fill('')));});}
  const csv=rows.map(row=>row.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\r\n'),url=URL.createObjectURL(new Blob([csv],{type:'text/csv'})),a=document.createElement('a');a.href=url;a.download='ammonia-storage-v055.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
 });

 function fillTrainingControls(s){
  $('storage-capacity-mode').value=s.capacity?.settings.mode||'legacy';fillCapacity(s.capacity?.settings);$('storage-compressorDemand').checked=s.operations.compressorDemand??true;
  for(const key of ['circuit','thermalMode','valveMode'])$('storage-'+key).value=s.operations[key];
  for(const key of ['compressorOn','drainEnabled'])$('storage-'+key).checked=s.operations[key];
  for(const key of ['receiverHeat','evaporatorHeat','condenserHeat','kp','ki'])$('storage-'+key).value=s.operations[key];
  $('storage-compressorSpeed').value=s.operations.speed*100;$('storage-manualOpening').value=s.operations.manualOpening*100;$('storage-superheatTarget').value=s.operations.superheatTarget*(units.T==='F'?1.8:1);
  $('storage-ambient').value=units.T==='F'?s.roomConfig.ambient*1.8+32:s.roomConfig.ambient;$('storage-gain').value=s.roomConfig.gain;$('storage-leakUA').value=s.roomConfig.leakUA;
 }
 training=AmmoniaTrainingApp.create($('storage-training'),{
  defaultActive:()=>AmmoniaPlantSnapshot().profile.id==='default',pause,refresh:render,isRunning:()=>running,advance:()=>$('storage-step').click(),toggleRun:()=>$(running?'storage-pause':'storage-start').click(),clearStop:()=>$('storage-clear').click(),
  load(recipe){const next=model.create(AmmoniaProfiles.DEFAULT,recipe.room,recipe.operations,recipe.capacity||null);if(recipe.warmup)model.advance(next,recipe.warmup);if(next.fault)throw Error('Training warmup reached a model stop.');state=next;fillTrainingControls(state);clearError();render();return state;},
  apply(o,r,c){model.update(state,o,r,c||null);fillTrainingControls(state);clearError();},
  event(s,reason,details){AmmoniaHistory.sample(s.history,model.record(s),model.observeCompressor(s),'training');AmmoniaHistory.event(s.history,s.time,'training',{reason,...details});}
 });
 const layout=document.querySelector('.layout'),live=$('view-live');
 function workspace(){layout.classList.toggle('live-workspace',!live.hidden);}
 new MutationObserver(workspace).observe(live,{attributes:true,attributeFilter:['hidden']});workspace();
 $('reference-toggle').addEventListener('click',()=>{const open=layout.classList.toggle('reference-open');$('reference-toggle').setAttribute('aria-expanded',String(open));$('reference-toggle').textContent=open?'Hide reference calculator':'Show reference calculator';});
 // Trial heat sources and feed tuning belong to the advanced disclosure, not the primary dashboard.
 const advanced=document.createElement('details');advanced.id='storage-advanced';advanced.className='disclosure';advanced.innerHTML='<summary>Advanced test heat and feed PI tuning</summary><div class="form-grid"></div>';
 const advancedGrid=advanced.querySelector('.form-grid');for(const id of ['storage-receiverHeat','storage-evaporatorHeat','storage-condenserHeat','storage-kp','storage-ki'])advancedGrid.append($(id).closest('.control'));
 $('storage-form').insertBefore(advanced,$('storage-form').querySelector('button[type=submit]'));
 const primary=$('storage-capacity-controls');for(const id of ['storage-compressorOn','storage-compressorSpeed'])primary.querySelector('.form-grid').append($(id).closest('.control'));
 $('storage-lab').querySelector('.card-body').insertBefore(primary,$('storage-capacity-readings'));
 primary.querySelectorAll('input,select').forEach(el=>el.setAttribute('form','storage-form'));
 const apply=document.createElement('button');apply.className='btn primary';apply.type='submit';apply.setAttribute('form','storage-form');apply.id='storage-apply-capacity';apply.textContent='Apply operating controls';primary.append(apply);
 document.querySelectorAll('input[type=checkbox]').forEach(el=>el.closest('label')?.classList.add('touch-check-label'));
 $('storage-capacity-mode').addEventListener('change',capacityAvailability);$('storage-capacity-controls').addEventListener('input',capacityDraft);
 fillCapacity();
 render();
})();
