(function(root){
'use strict';
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function create(container,adapter){
 const T=root.AmmoniaTraining;let attempt=null,plant=null,savedReport=null,hint=false,lastStatus=null;
 container.innerHTML='<div class="training-heading"><h3>Guided exercises</h3><span class="version">Default training model</span></div><p class="text">Loading/resetting replaces the connected run with fixed Default equipment and training room conditions. Apply Default in the equipment panel first. Custom profiles remain saved. Exercises use model inputs and computed outcomes; they are not plant operating procedures.</p><div class="training-toolbar"><label for="training-select">Exercise</label><select id="training-select">'+Object.entries(T.EXERCISES).map(([id,d])=>'<option value="'+id+'">'+esc(d.name)+'</option>').join('')+'</select><button type="button" class="btn primary" id="training-load">Load exercise</button><button type="button" class="btn" id="training-reset" disabled>Reset exercise</button><button type="button" class="btn" id="training-end" disabled>End exercise</button><button type="button" class="btn" id="training-export" disabled>Export attempt · JSON</button></div><p class="error" id="training-error" role="alert" hidden></p><p id="training-description" class="text"></p><p id="training-status" class="status" role="status">Choose an exercise and load its setup.</p><ol id="training-objectives" class="training-objectives"></ol><div class="training-toolbar"><button type="button" class="btn primary" id="training-disturbance" hidden>Apply disturbance</button><button type="button" class="btn" id="training-restore" hidden>Restore off-state controls</button><button type="button" class="btn" id="training-hint" aria-expanded="false">Show hint</button></div><p id="training-hint-text" class="training-hint" hidden></p><fieldset id="training-reflection"><legend>Reflection</legend><p id="training-question" class="text"></p><label for="training-answer">Your answer</label><select id="training-answer"></select><button type="button" class="btn" id="training-check" disabled>Check answer</button><p id="training-feedback" class="hint" role="status"></p></fieldset><div id="training-debrief" class="training-debrief" hidden></div><div class="training-toolbar"><button type="button" class="btn" id="training-advance" disabled>Advance 10 seconds</button><button type="button" class="btn" id="training-run" disabled>Start exercise playback</button><button type="button" class="btn" id="training-clear" hidden>Clear modeled stop</button></div><p class="hint">Use the connected run controls below to start, pause or advance. Successful objectives pause playback. Reset starts a fresh attempt; export before resetting or reloading to retain evidence.</p>';
 const $=id=>container.querySelector('#'+id),active=()=>attempt?.status==='active';
 function description(){const d=T.EXERCISES[$('training-select').value];$('training-description').textContent=d.description;}
 function render(){
  const id=attempt?.exercise||$('training-select').value,d=T.EXERCISES[id];
  $('training-select').disabled=active();$('training-load').disabled=!adapter.defaultActive();$('training-reset').disabled=!attempt||!adapter.defaultActive();$('training-end').disabled=!active();$('training-export').disabled=!attempt;
  $('training-advance').disabled=!active()||!!plant?.fault;$('training-run').disabled=!active()||!!plant?.fault;$('training-run').textContent=adapter.isRunning()?'Pause exercise playback':'Start exercise playback';$('training-clear').hidden=attempt?.exercise!=='hot'||!attempt.expectedFault;$('training-clear').disabled=!active()||!attempt.restored||!plant?.fault;
  $('training-check').disabled=!active();$('training-disturbance').hidden=!d.action||!attempt;$('training-disturbance').textContent=d.action||'Apply disturbance';$('training-disturbance').disabled=!active()||attempt.injectedAt!==null;
  $('training-restore').hidden=id!=='hot'||!attempt;$('training-restore').disabled=!active()||!attempt.expectedFault||attempt.restored;
  $('training-status').textContent=!adapter.defaultActive()?'Apply Default equipment before loading a supported exercise.':!attempt?'Choose an exercise and load its setup.':({active:'In progress',completed:'Objectives completed',stopped:'Stopped before completion',interrupted:'Exercise interrupted'})[attempt.status]+' · '+d.name+' · '+attempt.goals.filter(g=>g.met).length+'/'+attempt.goals.length+' objectives · began at '+attempt.startedAt.toFixed(3)+' simulated seconds'+(attempt.reason?' · '+attempt.reason:'');
  $('training-objectives').innerHTML=attempt?attempt.goals.map(g=>'<li class="'+(g.met?'met':'')+'">'+(g.met?'✓ ':'○ ')+esc(g.label)+(g.evidence?' <small>Observed at '+g.evidence.seconds.toFixed(3)+' s</small>':'')+'</li>').join(''):d.goals.map(g=>'<li>'+esc(g)+'</li>').join('');
  $('training-hint-text').textContent=d.hint;$('training-hint-text').hidden=!hint;$('training-hint').setAttribute('aria-expanded',String(hint));$('training-hint').textContent=hint?'Hide hint':'Show hint';
  $('training-question').textContent=d.question;
  if($('training-answer').dataset.exercise!==id){$('training-answer').dataset.exercise=id;$('training-answer').innerHTML='<option value="">Select an answer</option>'+d.answers.map((label,i)=>'<option value="'+i+'">'+esc(label)+'</option>').join('');$('training-feedback').textContent='';}
  $('training-debrief').hidden=!attempt||active();if(attempt&&!active())$('training-debrief').innerHTML='<h4>Debrief · '+esc(d.name)+'</h4><p class="text">'+esc(d.debrief)+'</p><p class="text">'+esc(attempt.status==='completed'?'Measured objectives and reflection were met.':attempt.reason||'The attempt ended before all objectives were met.')+'</p><p class="hint">The exported attempt links objective evidence to SI observations and original stop events. Exercise completion does not establish measured plant accuracy.</p>';
 }
 function finalize(){if(!attempt||active())return;if(lastStatus===attempt.status)return;lastStatus=attempt.status;if(plant)adapter.event(plant,'Exercise '+attempt.status,{exercise:attempt.exercise,reason:attempt.reason,endedAt:attempt.endedAt});adapter.pause('Exercise '+attempt.status);if(plant)savedReport=T.report(attempt,plant);}
 function load(id){
  try{
   if(!adapter.defaultActive())throw Error('Apply Default equipment before loading this exercise.');
   adapter.pause('Loading exercise');attempt=null;plant=adapter.load(T.setup(id));attempt=T.start(id,plant);savedReport=null;lastStatus=null;hint=false;$('training-answer').dataset.exercise='';$('training-feedback').textContent='';$('training-error').hidden=true;adapter.event(plant,'Exercise loaded',{exercise:id,warmupSeconds:T.EXERCISES[id].warmup});render();adapter.refresh();
  }catch(e){$('training-error').textContent=e.message;$('training-error').hidden=false;render();}
 }
 $('training-load').addEventListener('click',()=>load($('training-select').value));$('training-reset').addEventListener('click',()=>load(attempt.exercise));
 $('training-select').addEventListener('change',()=>{description();render();});
 $('training-end').addEventListener('click',()=>{if(!active())return;T.finish(attempt,'interrupted',plant.time,'Ended by learner.');finalize();render();});
 $('training-disturbance').addEventListener('click',()=>{try{const d=T.EXERCISES[attempt.exercise];adapter.pause('Applying exercise disturbance');adapter.apply(d.operations,d.boundary);T.injected(attempt,plant);adapter.event(plant,'Exercise disturbance applied',{exercise:attempt.exercise});update(plant);adapter.refresh();}catch(e){$('training-error').textContent=e.message;$('training-error').hidden=false;}});
 $('training-restore').addEventListener('click',()=>{try{adapter.pause('Restoring off-state controls');adapter.apply({compressorOn:false,valveMode:'closed'},{ambient:25});T.restored(attempt,plant);adapter.event(plant,'Exercise off-state controls restored',{exercise:attempt.exercise});update(plant);adapter.refresh();}catch(e){$('training-error').textContent=e.message;$('training-error').hidden=false;}});
 $('training-advance').addEventListener('click',()=>adapter.advance());$('training-run').addEventListener('click',()=>adapter.toggleRun());$('training-clear').addEventListener('click',()=>adapter.clearStop());
 $('training-hint').addEventListener('click',()=>{hint=!hint;render();});
 $('training-check').addEventListener('click',()=>{try{if(!$('training-answer').value)throw Error('Select a reflection answer.');const correct=T.answer(attempt,Number($('training-answer').value),plant.time);$('training-feedback').textContent=correct?'Correct. Measured objectives must also be met.':'Try again; inspect the evidence and hint.';adapter.event(plant,'Exercise reflection checked',{exercise:attempt.exercise,correct});update(plant);adapter.refresh();$('training-error').hidden=true;}catch(e){$('training-error').textContent=e.message;$('training-error').hidden=false;}});
 $('training-export').addEventListener('click',()=>{if(!attempt)return;const report=savedReport||T.report(attempt,plant),url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='ammonia-training-'+attempt.exercise+'-v050-stage3.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
 function update(s){if(active()&&s===plant){T.observe(attempt,s);finalize();}render();}
 function interrupt(reason){if(active()){T.finish(attempt,'interrupted',plant.time,reason);finalize();}render();}
 description();render();return {update,interrupt};
}
root.AmmoniaTrainingApp={create};
})(typeof globalThis!=='undefined'?globalThis:this);
