const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),{chromium,webkit,devices}=require('playwright'),{launchOptions}=require('./browser-helpers.cjs');
(async()=>{const which=process.env.TEST_BROWSER==='webkit'?'webkit':'chromium',browser=await(which==='webkit'?webkit:chromium).launch(which==='webkit'?{headless:true}:launchOptions);try{
 const page=await browser.newPage({...devices['iPad (gen 7)']}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{Array.prototype.at=undefined;});await page.goto(process.env.TEST_URL);assert(await page.locator('#startup-notice').isHidden());await page.locator('#tab-live').click();await page.locator('#storage-example').click();await page.locator('#storage-step').click();
 const before=await page.locator('#storage-states').innerHTML(),clock=await page.locator('#storage-clock').textContent();
 const results=await page.evaluate(()=>{
  const C=AmmoniaCapacity,p=AmmoniaProfiles.DEFAULT,input={pressureBarAbsolute:2.5},s=C.create(p,{mode:'auto'},{running:true,speed:.7});C.advance(s,1,input);C.advance(s,10,{pressureBarAbsolute:3.5});const high=C.record(s);C.advance(s,10,{pressureBarAbsolute:1.5});const low=C.record(s),old=s.speed;C.update(s,{mode:'manual'});const switched=C.record(s);
  const stop={kind:'domain',message:'Original domain evidence',seconds:s.time,readings:{pressure:1.5}},time=s.time;C.advance(s,60,{pressureBarAbsolute:1.5,stop});const inhibited=C.record(s);const timers=C.create(p,{minOff:2,startDelay:1,minOn:2});C.advance(timers,2,input);const waiting=C.record(timers);C.advance(timers,1,input);const started=C.record(timers);C.advance(timers,1,{...input,enabled:false});const disabled=C.record(timers);
  const oldState=JSON.stringify(s);let rejected=false;try{C.update(s,{suctionTarget:.4});}catch{rejected=true;}return {high,low,switched,old,inhibited,time,waiting,started,disabled,rejected,atomic:oldState===JSON.stringify(s)};
 });
 assert(results.high.actualSpeed>.7&&results.low.actualSpeed<results.high.actualSpeed);assert(Math.abs(results.switched.actualSpeed-results.old)<1e-8);assert.equal(results.inhibited.actualSpeed,0);assert.equal(results.inhibited.seconds,results.time);assert.equal(results.inhibited.stop.kind,'domain');assert.equal(results.waiting.reason,'Start delay');assert(results.started.running);assert(!results.disabled.running);assert(results.rejected&&results.atomic);
 const coupled=await page.evaluate(()=>{
  const engine=AmmoniaEngine.createEngine(JSON.parse(document.getElementById('property-data').textContent)),model=AmmoniaStorage.createStorage(engine,AmmoniaProfiles);
  const s=model.create(AmmoniaProfiles.DEFAULT,{}, {circuit:'circulating',thermalMode:'air',compressorOn:true,speed:.7,valveMode:'auto'},{mode:'auto'});
  model.advance(s,3);return {r:model.record(s),events:s.history.events.length,samples:s.history.samples};
 });
 assert.equal(coupled.r.capacity.seconds,coupled.r.seconds);assert(!coupled.r.fault);assert(Math.abs(coupled.r.massResidualKg)<1e-8);assert(Math.abs(coupled.r.energyResidualKJ)<1e-6);assert.equal(coupled.r.operations.speed,.7);assert(coupled.samples.every(s=>s.capacity));assert.equal(coupled.events,1);
 assert.equal(await page.locator('#storage-states').innerHTML(),before,'Dormant foundation cannot change plant vessels');assert.equal(await page.locator('#storage-clock').textContent(),clock);assert.equal(await page.locator('#storage-compressorSpeed').inputValue(),'70');assert.equal(await page.locator('#temperature-unit').inputValue(),'F');assert.equal(await page.locator('#pressure-unit').inputValue(),'psig');
 const offline=await browser.newPage();offline.on('pageerror',e=>errors.push(e.message));await offline.route(/^https?:/,r=>r.abort());await offline.setContent(fs.readFileSync(path.resolve(__dirname,'../index.html'),'utf8'));const standalone=await offline.evaluate(()=>{const s=AmmoniaCapacity.create(AmmoniaProfiles.DEFAULT,{minOff:0,startDelay:0});return AmmoniaCapacity.advance(s,1,{pressureBarAbsolute:2.5});});assert(standalone.running);assert.equal(standalone.mode,'manual');assert.deepEqual(errors,[]);
 console.log('PASS: '+which+' independent capacity module, automatic direction, switching, delays, stop priority, atomic rejection, SI telemetry, older-browser/offline bundle and unchanged connected controls/readings.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
