const assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const {chromium,webkit,devices}=require('playwright'),{launchOptions}=require('./browser-helpers.cjs');
const P=require('../equipment-profiles'),engine=require('../engine').createEngine(require('../properties.json')),model=require('../storage-engine').createStorage(engine,P);
(async()=>{
 const which=process.env.TEST_BROWSER==='webkit'?'webkit':'chromium',browser=await (which==='webkit'?webkit:chromium).launch(which==='webkit'?{headless:true}:launchOptions);
 try{
  const page=await browser.newPage({...devices['iPad (gen 7)'],acceptDownloads:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{Array.prototype.at=undefined;});await page.clock.install();await page.goto(process.env.TEST_URL);await page.locator('#tab-live').click();await page.locator('#storage-configuration summary').first().click();assert(await page.locator('#storage-history-export').isDisabled());
  await page.locator('#storage-example').click();await page.locator('#storage-trend-group').selectOption('all');await page.locator('#storage-step').click();assert.equal(await page.locator('.history-chart').count(),6);assert.match(await page.locator('#storage-trend-time').textContent(),/10.0000 s/);assert.match(await page.locator('#storage-events').textContent(),/Manual advance/);
  const s=model.create(P.DEFAULT,{}, {circuit:'circulating',thermalMode:'air',compressorOn:true,speed:.7,valveMode:'auto'});model.advance(s,10);const outlet=(s.states.outlet.p-1.01325)*14.503773773;assert.equal(await page.locator('[data-group="pressure"] [data-value="outlet"]').textContent(),outlet.toFixed(2)+' psig');
  await page.locator('#storage-trend-group').selectOption('superheat');assert.equal(await page.locator('.history-chart').count(),1);await page.locator('#storage-trend-prev').click();assert(await page.locator('#storage-trend-follow').isChecked()===false);const pinned=await page.locator('#storage-trend-time').textContent();await page.locator('#storage-start').click();await page.clock.runFor(1000);assert.equal(await page.locator('#storage-trend-time').textContent(),pinned);await page.locator('#storage-pause').click();assert.match(await page.locator('#storage-events').textContent(),/Playback paused/);
  await page.locator('#storage-trend-follow').check();const follows=await page.locator('#storage-trend-time').textContent();assert.notEqual(follows,pinned);await page.locator('[data-series="superheat:targetSuperheat"]').uncheck();assert.equal(await page.locator('[data-curve="targetSuperheat"]').count(),0);await page.locator('[data-series="superheat:targetSuperheat"]').check();assert.equal(await page.locator('[data-curve="targetSuperheat"]').count(),1);
  await page.locator('#storage-gain').fill('10');await page.locator('#storage-form button[type="submit"]').click();await page.locator('#storage-event-filter').selectOption('controls');assert.equal(await page.locator('#storage-events tr[data-event-id]').count(),1);await page.locator('#storage-events [data-event]').click();assert.match(await page.locator('#storage-event-detail').textContent(),/Room heat gain: 2.0000 kW → 10.0000 kW/);
  const count=await page.locator('#storage-event-count').textContent();await page.locator('#storage-form button[type="submit"]').click();assert.equal(await page.locator('#storage-event-count').textContent(),count);await page.locator('#storage-ambient').fill('200');await page.locator('#storage-form button[type="submit"]').click();assert(await page.locator('#storage-error').isVisible());assert.equal(await page.locator('#storage-event-count').textContent(),count);await page.locator('#storage-ambient').fill('77');await page.locator('#storage-form button[type="submit"]').click();
  const time=await page.locator('#storage-trend-time').textContent();await page.locator('#temperature-unit').selectOption('C');await page.locator('#pressure-unit').selectOption('bara');assert.equal(await page.locator('#storage-trend-time').textContent(),time);assert.match(await page.locator('[data-group="superheat"] [data-value="actualSuperheat"]').textContent(),/ K$/);await page.locator('#storage-trend-window').selectOption('60');await page.locator('#storage-trend-group').selectOption('pressure');assert.match(await page.locator('[data-value="outlet"]').textContent(),/bar\(a\)/);
  const download=page.waitForEvent('download');await page.locator('#storage-history-export').click();const file=path.join(__dirname,'history-'+which+'.csv');await (await download).saveAs(file);const csv=fs.readFileSync(file,'utf8');assert.match(csv,/"sample"/);assert.match(csv,/"event"/);assert.match(csv,/gain/);assert.match(csv,/roomBoundary/);assert.match(csv,/speedSetting/);
  const csvRows=csv.split(/\r?\n/).filter(Boolean).map(line=>[...line.matchAll(/"((?:[^"]|"")*)"(?:,|$)/g)].map(m=>m[1].replace(/""/g,'"'))),header=csvRows[4],exported=csvRows.slice(5).find(row=>row[0]==='sample'&&Math.abs(Number(row[2])-10)<1e-8);assert(csvRows.slice(5).every(row=>row.length===header.length));assert(Math.abs(Number(exported[header.indexOf('outlet bar absolute')])-s.states.outlet.p)<1e-8);
  await page.locator('#storage-trend-cursor').focus();await page.keyboard.press('Home');await page.keyboard.press('ArrowRight');assert.match(await page.locator('#storage-trend-time').textContent(),/Pinned inspection/);await page.locator('.history-plot svg').click({position:{x:150,y:80}});assert(await page.locator('#storage-trend-follow').isChecked()===false);
  await page.locator('#storage-event-filter').selectOption('all');await page.locator('#storage-example').click();assert.equal(await page.locator('#storage-events tr[data-event-id]').count(),1);assert.match(await page.locator('#storage-history-retention').textContent(),/1 retained samples/);
  await page.locator('#profile-new').click();await page.locator('#profile-name').fill('History trip evidence');await page.locator('#profile-highTrip').fill('10');await page.locator('#profile-save').click();await page.locator('#profile-use').click();assert(await page.locator('#storage-history-export').isDisabled());await page.locator('#storage-example').click();await page.locator('#storage-step').click();await page.locator('#storage-event-filter').selectOption('stops');assert.equal(await page.locator('#storage-events tr[data-event-id]').count(),1);await page.locator('#storage-events [data-event]').click();assert.match(await page.locator('#storage-event-detail').textContent(),/High discharge pressure/);assert.match(await page.locator('#storage-event-detail').textContent(),/0.0000 s/);
  await page.locator('#storage-compressorOn').uncheck();await page.locator('#storage-form button[type="submit"]').click();await page.locator('#storage-clear').click();assert.equal(await page.locator('#storage-events tr[data-event-id]').count(),2);await page.locator('#storage-events [data-event]').first().click();assert.match(await page.locator('#storage-event-detail').textContent(),/does not prove the cause is corrected/);await page.locator('#storage-events [data-event]').last().click();assert.match(await page.locator('#storage-event-detail').textContent(),/High discharge pressure/);
  await page.locator('#profile-select').selectOption('default');await page.locator('#profile-use').click();await page.locator('#storage-circuit').selectOption('closed');await page.locator('#storage-initialize').click();await page.locator('#storage-trend-group').selectOption('superheat');assert.equal(await page.locator('[data-curve="actualSuperheat"]').count(),0);assert.match(await page.locator('.history-plot svg').textContent(),/No available/);
  await page.locator('#storage-example').click();await page.locator('#storage-step').click();await page.locator('#storage-trend-group').selectOption('all');await page.locator('#storage-event-filter').selectOption('all');for(const size of [{width:1024,height:1366},{width:768,height:1024},{width:390,height:844}]){await page.setViewportSize(size);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert(await page.locator('#storage-trend-cursor').isVisible());}
  await page.locator('#storage-trends').screenshot({path:path.join(__dirname,'history-'+which+'-mobile.png')});
  const offline=await browser.newPage();await offline.route(/^https?:/,route=>route.abort());await offline.setContent(fs.readFileSync(path.resolve(__dirname,'../index.html'),'utf8'));await offline.locator('#tab-live').click();await offline.locator('#storage-example').click();await offline.locator('#storage-step').click();assert.match(await offline.locator('#storage-trend-time').textContent(),/10.0000 s/);assert.deepEqual(errors,[]);
  console.log('PASS: '+which+' synchronized history/model values, pinned/follow cursor, curve visibility, exact control events, invalid/no-op rejection, units, SI CSV, keyboard/touch inspection, reset, trip/clear evidence, unavailable isolated readings, tablet/mobile and offline history.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
