/* Integrated release checks: assertions express physical/accounting contracts. */
const assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const P=require('../equipment-profiles'),e=require('../engine').createEngine(require('../properties.json'));
const make=n=>require('../storage-engine').createStorage(e,P,n),d=make();
const ops={circuit:'circulating',thermalMode:'air',compressorOn:true,speed:.7,valveMode:'auto'};
const scenarios=[];
function check(name,s,expected=null){
 const r=d.record(s);assert.equal(s.fault?.kind??null,expected,name+': '+s.fault?.message);
 assert(Math.abs(r.massResidualKg)<1e-8,name+' charge balance');assert(Math.abs(r.energyResidualKJ)<1e-6,name+' combined energy balance');
 assert(Object.values(s.vessels).every(v=>v.massKg>0&&Number.isFinite(v.internalEnergyKJ)),name+' valid inventories');
 assert(Object.values(s.states).every(v=>v.p>=.3&&v.p<=35),name+' bounded states');assert(r.controller.opening>=0&&r.controller.opening<=1);
 if(s.fault){assert.equal(s.pending,0);assert.equal(s.fault.seconds,s.time);assert.equal(s.fault.readings.room,s.T);assert.equal(s.fault.readings.pressure,(s.states.outlet||s.states.evaporator).p);assert.equal(s.fault.readings.condensing,s.states.condenser.p);const before=JSON.stringify(s);d.advance(s,60);assert.equal(JSON.stringify(s),before,name+' stopped playback');}
 scenarios.push({name,seconds:r.seconds,fault:r.fault?.kind??null,message:r.fault?.message??null,roomC:r.T,suctionBar:r.vessels.outlet?.p??r.vessels.evaporator.p,superheatK:r.flows?.superheat??null,massResidualKg:r.massResidualKg,energyResidualKJ:r.energyResidualKJ});return r;
}
const normal=d.create(P.DEFAULT,{},ops);d.advance(normal,120);const n=check('Automatic circulating startup',normal);assert(n.flows.feed.massFlow>0&&n.flows.drain.massFlow>0);assert(n.electricalKWh>0&&normal.T<15);
// Apply a load perturbation through the prescribed room-load boundary, preserving room C and initial energy.
const loaded=d.create(P.DEFAULT,{},ops);d.advance(loaded,30);const loadTime=loaded.time,loadEnergy=loaded.externalHeatKJ;d.update(loaded,{}, {gain:20});assert.equal(loaded.time,loadTime);assert.equal(loaded.externalHeatKJ,loadEnergy);d.advance(loaded,90);check('Higher room load',loaded);assert(loaded.T>normal.T);
const manual=d.create(P.DEFAULT,{}, {...ops,valveMode:'manual',manualOpening:1});d.advance(manual,120);const m=check('Manual full feed',manual);assert(m.flows.feed.massFlow>n.flows.feed.massFlow);
const blocked=d.create(P.DEFAULT,{}, {...ops,drainEnabled:false});d.advance(blocked,120);const b=check('Condenser drain disabled',blocked);assert.equal(b.flows.drain.massFlow,0);assert(b.vessels.condenser.massKg>n.vessels.condenser.massKg);
const speed=d.create(P.DEFAULT,{}, {...ops,speed:1});d.advance(speed,120);const f=check('Full compressor speed',speed);assert(f.electricalKWh>n.electricalKWh);
const shutdown=d.create(P.DEFAULT,{},ops);d.advance(shutdown,60);d.update(shutdown,{compressorOn:false,valveMode:'closed'});const before=d.record(shutdown);d.advance(shutdown,20);const off=check('Shutdown with retained pressure',shutdown);assert.equal(off.electricalKWh,before.electricalKWh);assert.equal(off.flows.command,0);assert(off.controller.opening<before.controller.opening);assert(off.vessels.outlet.p>0);
d.update(shutdown,{compressorOn:true,valveMode:'auto'});d.advance(shutdown,1);const restarted=check('Wet restart domain boundary',shutdown,'domain');assert.match(shutdown.fault.message,/Wet compressor suction/);assert(shutdown.fault.attemptedReadings);assert.notEqual(shutdown.fault.attemptedReadings.pressure,shutdown.fault.readings.pressure);
d.update(shutdown,{compressorOn:false,valveMode:'closed'});d.clearFault(shutdown);d.advance(shutdown,1);check('Domain stop recovery with compressor off',shutdown);assert(shutdown.time>restarted.seconds);
for(const [name,patch,message]of [['High-pressure trip',{highTrip:10},'High discharge pressure'],['Low-pressure trip',{lowTrip:3},'Low suction pressure'],['Discharge-temperature trip',{dischargeTrip:80},'High discharge temperature']]){
 const p=P.copy(P.DEFAULT);Object.assign(p.equipment,patch);const s=d.create(p,{},ops);d.advance(s,60);check(name,s,'equipment');assert.equal(s.time,0);assert.equal(s.fault.message,message);assert.deepEqual(s.fault.limits,p.equipment);
 d.update(s,{compressorOn:false});d.clearFault(s);d.advance(s,1);check(name+' recovery',s);
}
const starved=d.create(P.DEFAULT,{}, {...ops,valveMode:'closed'});d.advance(starved,60);check('Feed shutoff reaches thermal trip',starved,'equipment');assert.equal(starved.fault.message,'High discharge temperature');assert.equal(d.record(starved).flows.feed.massFlow,0);
const batches=[1,60].map(chunk=>{const s=d.create(P.DEFAULT,{}, {...ops,valveMode:'closed'});while(!s.fault)d.advance(s,chunk);return s;});assert.deepEqual(batches[0].vessels,batches[1].vessels);assert.deepEqual(batches[0].fault,batches[1].fault);
const overfill=P.copy(P.DEFAULT);overfill.inventory.initialization.liquidFractions.evaporator=.95;assert.throws(()=>d.create(overfill,{},ops),/vapor space/);
const dry=P.copy(P.DEFAULT);dry.inventory.initialization.liquidFractions.receiver=0;dry.inventory.initialization.liquidFractions.condenser=0;const unavailable=d.create(dry,{}, {...ops,compressorOn:false,valveMode:'manual',manualOpening:1});const initial=d.record(unavailable);assert.equal(initial.flows.feed.massFlow,0);assert.equal(initial.flows.drain.massFlow,0);d.advance(unavailable,1);check('Vapor-only liquid sources',unavailable);
const fixed=P.copy(P.DEFAULT);fixed.equipment.performanceMode='fixed';fixed.equipment.displacement=120;fixed.connections.feedAreaM2=3e-5;const custom=d.create(fixed,{},ops);d.advance(custom,20);check('Custom fixed-efficiency equipment',custom);assert.notEqual(custom.electricalKWh,normal.rows[0].electricalKWh);
// Force a bounded inversion stop and deliberately strict numerical tolerance.
const limitProfile=P.copy(P.DEFAULT);limitProfile.inventory.initialization.liquidFractions.receiver=1;const limit=d.create(limitProfile,{}, {receiverHeat:100});d.advance(limit,10);check('Compressed-liquid property boundary',limit,'domain');
const strict=make({maxStep:.1,minStep:.1,tolerance:1e-12}),solver=strict.create(P.DEFAULT,{},ops);strict.advance(solver,1);check('Explicit integration tolerance limit',solver,'solver');assert.equal(solver.time,0);
const hotModels=[.1,.05,.025].map(h=>{const model=make({maxStep:h}),s=model.create(P.DEFAULT,{ambient:40},ops);model.advance(s,90);check('Hot condenser phase exhaustion · step '+h+' s',s,'equipment');assert.equal(s.fault.message,'High discharge temperature');assert(s.acceptedSteps<10000,'No dry/wet numerical chattering');return s;});
assert(Math.abs(hotModels[0].time-hotModels[2].time)<.1);assert(Math.abs(hotModels[0].states.condenser.p-hotModels[2].states.condenser.p)<.005);
const receiverDry=P.copy(P.DEFAULT);receiverDry.inventory.initialization.liquidFractions.receiver=0;const exhausted=d.create(receiverDry,{}, {...ops,valveMode:'manual',manualOpening:1});d.advance(exhausted,90);check('Receiver starvation reaches thermal trip',exhausted,'equipment');assert.equal(exhausted.fault.message,'High discharge temperature');assert(exhausted.acceptedSteps<10000);assert(Object.values(exhausted.vessels).every(v=>v.massKg>0));
const unchanged=JSON.stringify({o:normal.operations,room:normal.roomConfig,controller:normal.controller,rows:normal.rows});for(const patch of [{ambient:46},{gain:-1},{leakUA:NaN},{initial:20},{thermalMass:2}])assert.throws(()=>d.update(normal,{speed:.8},patch));assert.equal(JSON.stringify({o:normal.operations,room:normal.roomConfig,controller:normal.controller,rows:normal.rows}),unchanged,'Invalid changes are atomic');
d.update(normal,{}, {ambient:30,gain:5,leakUA:.2});assert.deepEqual(normal.rows.at(-1).roomBoundary,{ambient:30,gain:5,leakUA:.2});assert.equal(normal.initialRoomConfig.ambient,25);d.advance(normal,1);check('Applied ambient / room boundaries',normal);
const run=(model,chunk)=>{const s=model.create(P.DEFAULT,{},ops);for(let t=0;t<30;t+=chunk)model.advance(s,chunk);assert(!s.fault);return s;};const a=run(d,30),c=run(d,1),fine=run(make({maxStep:.05,tolerance:5e-6}),30);assert.deepEqual(a.vessels,c.vessels);assert.deepEqual(a.controller,c.controller);const refinement={outletPressureBar:Math.abs(a.states.outlet.p-fine.states.outlet.p),roomK:Math.abs(a.T-fine.T),electricalRelative:Math.abs(a.electricalKWh/fine.electricalKWh-1)};assert(refinement.outletPressureBar<.001&&refinement.roomK<.0001&&refinement.electricalRelative<.001);
// Assertions above use full precision. Published evidence has declared display
// precision so harmless platform rounding cannot change the standalone bundle.
const round=(value,digits)=>Number(value.toFixed(digits));
const upper=value=>{if(value===0)return 0;const q=10**(Math.floor(Math.log10(Math.abs(value)))-1);return Number((Math.ceil(Math.abs(value)/q)*q).toPrecision(2));};
const published=scenarios.map(row=>({...row,seconds:round(row.seconds,3),roomC:round(row.roomC,3),suctionBar:round(row.suctionBar,3),superheatK:row.superheatK===null?null:round(row.superheatK,3),massResidualKg:round(row.massResidualKg,9),energyResidualKJ:round(row.energyResidualKJ,7)}));
const report={version:'0.4.5',passed:true,scope:'Numerical and accounting verification; generic equipment models, not measured plant validation.',reportPrecision:'Operating readings: 0.001 SI; case residuals: 1e-9 kg / 1e-7 kJ. Maximum residuals and refinement differences are upper bounds rounded up to two significant digits. Assertions use full precision.',scenarios:published,checks:{faultBatching:true,acceptedStateFaultEvidence:true,unavailableLiquid:true,infeasibleGeometry:true,playbackBatching:true},refinement:Object.fromEntries(Object.entries(refinement).map(([key,value])=>[key,upper(value)])),maxMassResidualKg:upper(Math.max(...scenarios.map(s=>Math.abs(s.massResidualKg)))),maxEnergyResidualKJ:upper(Math.max(...scenarios.map(s=>Math.abs(s.energyResidualKJ))))};
fs.writeFileSync(path.join(__dirname,'../integration-validation.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({passed:true,scenarios:scenarios.length,refinement,maxMassResidualKg:report.maxMassResidualKg,maxEnergyResidualKJ:report.maxEnergyResidualKJ},null,2));
