const fs=require('fs'),assert=require('node:assert/strict');
const {createEngine}=require('../engine.js');const data=require('../properties.json'),ref=require('./reference-cases.json');const e=createEngine(data);
const max={temperatureK:0,enthalpyPercent:0,entropyPercent:0,densityPercent:0,dischargeK:0,cycleCoolingPercent:0,cycleElectricalPercent:0,cycleCOPPercent:0,energyResidualKW:0,manufacturerFitK:0};
for(const f of ref.properties){const r=f.ref,a=e.statePT(r.p,r.T,f.kind==='liquid'?'liquid':undefined);for(const [key,label] of [['h','enthalpyPercent'],['s','entropyPercent'],['rho','densityPercent']])max[label]=Math.max(max[label],100*Math.abs(a[key]-r[key])/Math.max(1,Math.abs(r[key])));if(f.kind==='vapor'){assert(Math.abs(e.ph(r.p,r.h).T-r.T)<.12);assert(Math.abs(e.ps(r.p,r.s).T-r.T)<.12);}}
for(const r of ref.saturation)max.temperatureK=Math.max(max.temperatureK,Math.abs(e.sat(r.p).T-r.T));
let eligibleCycles=0,rejectedCycles=0;for(const f of ref.cycles){const r=f.ref;if(r.T2>e.sat(f.config.condensing).T+250){assert.throws(()=>e.solve(f.config));rejectedCycles++;continue;}const a=e.solve(f.config);eligibleCycles++;max.dischargeK=Math.max(max.dischargeK,Math.abs(a.states[1].T-r.T2));for(const [key,label] of [['Q','cycleCoolingPercent'],['electrical','cycleElectricalPercent'],['COP','cycleCOPPercent']])max[label]=Math.max(max[label],100*Math.abs(a[key]-r[key])/r[key]);max.energyResidualKW=Math.max(max.energyResidualKW,Math.abs(a.balance));assert(a.states[1].s>=a.states[0].s-1e-7);assert(a.COP<=a.carnot);assert(Math.abs(a.flashFraction-r.flash)<.001);}
// Independent manufacturer controller correlation derived from REFPROP 10, not an EOS identity test.
const manufacturer=[];for(let T=-40;T<=40;T+=5){const p=Math.exp(10.760-2307.3/(T+247.9));const calculated=e.sat(p).T;manufacturer.push({referenceTemperatureC:T,pressureBar:p,tableTemperatureC:calculated});max.manufacturerFitK=Math.max(max.manufacturerFitK,Math.abs(calculated-T));}
assert(max.temperatureK<.02);assert(max.enthalpyPercent<.05);assert(max.entropyPercent<.05);assert(max.densityPercent<.06);assert(max.dischargeK<.12);assert(max.cycleCoolingPercent<.05);assert(max.cycleElectricalPercent<.08);assert(max.cycleCOPPercent<.1);assert(max.energyResidualKW<1e-7);assert(max.manufacturerFitK<.8);
assert.throws(()=>e.sat(.1));assert.throws(()=>e.solve({pressure:0}));assert.throws(()=>e.solve({condensing:3}));assert.throws(()=>e.solve({subcool:0,liquidDrop:.5}));assert.throws(()=>e.solve({system:'flooded',evapSH:5}));
const r=e.solve({});const load=e.solve({flowMode:'load',load:100});assert(Math.abs(load.Q-100)<1e-8);
const disp=e.solve({flowMode:'displacement',displacement:180});assert(Math.abs(disp.m-180/3600*.75*disp.states[0].rho)<1e-8);
const ambient=e.solve({highMode:'ambient',ambient:25,approach:10});assert(Math.abs(ambient.high.T-35)<.02);
const fewerLosses=e.solve({etaIs:100,etaMotor:100});assert(fewerLosses.COP>r.COP);
const opts={initial:15,target:0,deadband:2,thermalMass:30,leakUA:.1,internalGain:2,hours:12};const trans=e.roomSimulation(r,opts);assert(trans.firstSetpoint>0);assert(trans.rows.every(x=>Number.isFinite(x.T)));assert(trans.finalT>=-1.01&&trans.finalT<=1.01);assert.throws(()=>e.roomSimulation(r,{...opts,target:-30}));
const noGain=e.roomSimulation(r,{initial:20,target:0,deadband:2,thermalMass:30,leakUA:0,internalGain:0,hours:12});assert(Math.abs(noGain.firstSetpoint-30000*20/r.Q/60)<1e-7);assert(Math.abs(noGain.energy*3600*r.COP-30000*(20-noGain.finalT))<1e-6);
const report={version:'0.2.0',engine:data.version,counts:{singlePhaseStates:ref.properties.length,saturationStates:ref.saturation.length,cycles:eligibleCycles,outOfDomainCyclesRejected:rejectedCycles,manufacturerCorrelationPoints:manufacturer.length},maxErrors:max,manufacturerSource:'https://assets.danfoss.com/documents/latest/493262/AM187286420404en-000702.pdf',notes:['Interpolation errors versus direct CoolProp at seeded unseen states; not total physical uncertainty.','Manufacturer comparison is agreement with a controller-fit correlation, not independent calorimetric validation.','NIST fluid data endpoint returned HTTP 403; no claim of direct NIST table validation.'],defaultResult:{Q:r.Q,COP:r.COP,electrical:r.electrical,dischargeTemperature:r.states[1].T},transient:{firstSetpointMinutes:trans.firstSetpoint,finalTemperatureC:trans.finalT}};
fs.writeFileSync(require('path').join(__dirname,'../validation.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
