const assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const {chromium}=require('playwright'),{launchOptions}=require('./browser-helpers.cjs');
(async()=>{
 const browser=await chromium.launch(launchOptions);
 try{
  const page=await browser.newPage({acceptDownloads:true,viewport:{width:1280,height:950}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(process.env.TEST_URL);await page.locator('#tab-live').click();
  assert.equal(await page.locator('#profile-select').inputValue(),'default');assert(await page.locator('#profile-edit').isDisabled());assert(await page.locator('#profile-delete').isDisabled());assert.equal(await page.locator('#live-displacement').getAttribute('readonly'),'');
  await page.locator('#profile-new').click();await page.locator('#profile-name').fill('Plant A <custom>');await page.locator('#profile-source-kind').selectOption('manufacturer');await page.locator('#profile-performance').selectOption('fixed');await page.locator('#profile-displacement').fill('120');await page.locator('#profile-evapUA').fill('8');await page.locator('#profile-condUA').fill('18');await page.locator('#profile-etaIs').fill('70');await page.locator('#profile-etaVol').fill('80');await page.locator('#profile-etaMotor').fill('96');
  await page.locator('#profile-save').click();assert(await page.locator('#profile-error').isVisible());assert.match(await page.locator('#profile-error').textContent(),/reference/);
  await page.locator('#profile-source').fill('Manufacturer nameplate ABC; efficiencies estimated');await page.locator('#profile-form details summary').click();await page.locator('#profile-volume-receiver').fill('.8');await page.locator('#profile-save').click();assert(await page.locator('#profile-form').isHidden());assert.match(await page.locator('#profile-active-label').textContent(),/Default/);assert.match(await page.locator('#profile-summary').textContent(),/not independently validated/);
  const customId=await page.locator('#profile-select').inputValue();await page.locator('#live-step').click();assert.match(await page.locator('#profile-use').textContent(),/reset/);await page.locator('#live-target').fill('35');await page.locator('#profile-use').click();assert.equal(await page.locator('#live-clock').textContent(),'00:00:00 simulated');assert.equal(await page.locator('#live-displacement').inputValue(),'120');assert.equal(await page.locator('#live-target').inputValue(),'35');assert.match(await page.locator('#profile-active-label').textContent(),/revision 1/);
  await page.locator('#live-step').click();assert.match(await page.locator('#live-balance').textContent(),/70.0 \/ 80.0%/);const currentPower=await page.locator('#live-metrics .metric').nth(5).textContent();
  await page.locator('#profile-edit').click();await page.locator('#profile-displacement').fill('240');await page.locator('#profile-save').click();assert.match(await page.locator('#profile-active-label').textContent(),/revision 1/);assert.equal(await page.locator('#live-displacement').inputValue(),'120');assert.equal(await page.locator('#live-metrics .metric').nth(5).textContent(),currentPower);await page.locator('#profile-use').click();assert.match(await page.locator('#profile-active-label').textContent(),/revision 2/);assert.equal(await page.locator('#live-displacement').inputValue(),'240');
  let promise=page.waitForEvent('download');await page.locator('#profile-export').click();let download=await promise;const filename=path.join(__dirname,'profile-export.json');await download.saveAs(filename);const exported=JSON.parse(fs.readFileSync(filename));assert.equal(exported.schemaVersion,1);assert.equal(exported.equipment.displacement,240);assert.equal(exported.futureVolumes.receiver,.8);assert(!('target' in exported.equipment));assert(!('ambient' in exported.equipment));assert.equal(exported.equipment.lowTrip,.4);
  await page.locator('#temperature-unit').selectOption('C');await page.locator('#pressure-unit').selectOption('bara');await page.locator('#profile-edit').click();assert.equal(await page.locator('#profile-dischargeTrip').inputValue(),'170');assert.equal(await page.locator('#profile-lowTrip').inputValue(),'0.4');await page.locator('#temperature-unit').selectOption('F');assert.equal(await page.locator('#profile-dischargeTrip').inputValue(),'338');await page.locator('#profile-cancel').click();
  await page.reload();await page.locator('#tab-live').click();assert.equal(await page.locator('#profile-select').inputValue(),customId);assert.match(await page.locator('#profile-active-label').textContent(),/revision 2/);assert.equal(await page.locator('#live-clock').textContent(),'00:00:00 simulated');assert.equal(await page.locator('#live-displacement').inputValue(),'240');
  await page.locator('#profile-duplicate').click();await page.locator('#profile-name').fill('Plant B');await page.locator('#profile-save').click();const copyId=await page.locator('#profile-select').inputValue();assert.notEqual(copyId,customId);await page.locator('#profile-delete').click();assert.equal(await page.locator('#profile-select option').count(),2);
  await page.locator('#profile-import-file').setInputFiles(filename);await page.waitForFunction(()=>document.querySelectorAll('#profile-select option').length===3);assert.notEqual(await page.locator('#profile-select').inputValue(),customId);assert.equal(await page.locator('#live-displacement').inputValue(),'240');
  const invalid=path.join(__dirname,'profile-invalid.json');fs.writeFileSync(invalid,JSON.stringify({...exported,schemaVersion:99}));await page.locator('#profile-import-file').setInputFiles(invalid);await page.waitForFunction(()=>document.querySelector('#profile-status').textContent.includes('Import rejected'));assert.equal(await page.locator('#profile-select option').count(),3);
  await page.locator('#profile-select').selectOption(customId);await page.locator('#profile-delete').click();assert.match(await page.locator('#profile-status').textContent(),/another profile/);await page.locator('#profile-select').selectOption('default');await page.locator('#profile-use').click();assert.equal(await page.locator('#live-displacement').inputValue(),'180');assert(await page.locator('#profile-edit').isDisabled());await page.locator('#profile-select').selectOption(customId);await page.locator('#profile-delete').click();assert.equal(await page.locator('#profile-select option').count(),2);
  await page.setViewportSize({width:390,height:844});await page.locator('#profile-new').click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(__dirname,'profiles-mobile.png'),fullPage:true});await page.locator('#profile-name').fill('X'.repeat(80));await page.locator('#profile-save').click();await page.locator('#profile-use').click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);
  const blocked=await browser.newPage();await blocked.addInitScript(()=>{Storage.prototype.setItem=function(){throw new Error('Storage blocked');};});await blocked.goto(process.env.TEST_URL);await blocked.locator('#tab-live').click();await blocked.locator('#profile-new').click();await blocked.locator('#profile-name').fill('Session profile');await blocked.locator('#profile-save').click();assert.match(await blocked.locator('#profile-status').textContent(),/session only/);await blocked.locator('#profile-use').click();assert.match(await blocked.locator('#profile-active-label').textContent(),/Session profile/);
  const corrupt=await browser.newPage();await corrupt.addInitScript(()=>localStorage.setItem('ammonia-lab-equipment-v1','{"schemaVersion":999}'));await corrupt.goto(process.env.TEST_URL);await corrupt.locator('#tab-live').click();assert.equal(await corrupt.locator('#profile-select').inputValue(),'default');assert.match(await corrupt.locator('#profile-status').textContent(),/could not be read/);
  console.log('PASS: Default protection, custom edits/revisions, fixed efficiency application, reset-on-use, operating-setting separation, profile JSON, unit conversions, persistence, duplication/deletion, rejected imports, unavailable/corrupt storage and mobile editor.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
