const assert=require('node:assert/strict'),P=require('../equipment-profiles');
const engine=require('../engine').createEngine(require('../properties.json')),d=require('../dynamic-engine').createDynamic(engine);
assert(Object.isFrozen(P.DEFAULT)&&Object.isFrozen(P.DEFAULT.equipment));
const custom=P.duplicate(P.DEFAULT,'Test system');custom.equipment.displacement=120;custom.equipment.performanceMode='fixed';custom.equipment.etaMotor=96;custom.futureVolumes.receiver=.5;
const p=P.normalize(custom);assert.equal(p.revision,1);assert.equal(p.futureVolumes.receiver,.5);assert.equal(P.DEFAULT.equipment.displacement,180);
const revised=P.revise(p,{...p,name:'Updated system'});assert.equal(revised.revision,2);assert.equal(revised.id,p.id);assert.equal(revised.createdAt,p.createdAt);
assert.throws(()=>P.revise(P.DEFAULT,P.DEFAULT),/read-only/);assert.throws(()=>P.normalize({...p,schemaVersion:2}),/version/);
assert.throws(()=>P.normalize({...p,arrangement:'flooded'}),/single-stage DX/);assert.throws(()=>P.normalize({...p,sourceKind:'manufacturer',source:''}),/reference/);
for(const equipment of [{...p.equipment,compressors:1.5},{...p.equipment,evapUA:NaN},{...p.equipment,etaIs:0},{...p.equipment,performanceMode:'manufacturer-map'},{...p.equipment,displacement:'120'}])assert.throws(()=>P.normalize({...p,equipment}));
assert.throws(()=>P.normalize({...p,futureVolumes:{...p.futureVolumes,receiver:-1}}));
const imported=P.imported(JSON.parse(JSON.stringify(p)));assert.notEqual(imported.id,p.id);assert.deepEqual(imported.equipment,p.equipment);
const restored=P.restore({schemaVersion:1,activeId:p.id,profiles:[p,{...p,id:'broken',equipment:{}},p,P.DEFAULT]});assert.equal(restored.profiles.length,1);assert.equal(restored.rejected,3);assert.equal(restored.activeId,p.id);
const config=P.apply({initial:20,target:2,ambient:30,kp:.7,mode:'manual'},p);assert.equal(config.initial,20);assert.equal(config.target,2);assert.equal(config.kp,.7);assert.equal(config.displacement,120);assert(!('futureVolumes' in config));
const baseline=d.coupled(15,P.apply({},P.DEFAULT),.7);const original=d.coupled(15,{},.7);assert.equal(baseline.r.Q,original.r.Q);
const fixed=d.coupled(15,config,.7);assert.equal(fixed.etaIs,.75);assert.equal(fixed.etaVol,.75);assert(Math.abs(fixed.r.electrical-fixed.r.W/.96)<1e-8);assert.notEqual(fixed.r.Q,baseline.r.Q);assert(Math.max(...fixed.residual.map(Math.abs))<1e-6);
const source=P.copy(p);source.sourceKind='manufacturer';source.source='Nameplate data, document ABC';assert.equal(P.normalize(source).sourceKind,'manufacturer');assert.equal(source.equipment.performanceMode,'fixed');
console.log('PASS: immutable Default, schema/types/ranges, revisions, import IDs, malformed storage, operating-setting isolation, unused volumes, Default physics parity, and applied fixed-efficiency specifications.');
