const assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const {chromium,webkit,devices}=require('playwright'),{launchOptions}=require('./browser-helpers.cjs');
const engine=process.env.TEST_BROWSER==='webkit'?'webkit':'chromium';
function csvRows(csv){return csv.split(/\r?\n/).filter(Boolean).map(line=>[...line.matchAll(/"((?:[^"]|"")*)"(?:,|$)/g)].map(m=>m[1].replace(/""/g,'"')));}
(async()=>{
 const browser=await (engine==='webkit'?webkit:chromium).launch(engine==='webkit'?{headless:true}:launchOptions);
 try{
  const context=await browser.newContext({...devices['iPad (gen 7)'],acceptDownloads:true}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.clock.install();await page.goto(process.env.TEST_URL);assert(await page.locator('#startup-notice').isHidden());
  for(const tab of ['live','validation','room','thermo','cycle','live'])await page.locator('#tab-'+tab).click();assert(await page.locator('#runtime-notice').isHidden());
  await page.locator('#storage-example').click();assert(await page.locator('#storage-error').isHidden());assert.equal(await page.locator('#storage-circuit').inputValue(),'circulating');assert.equal(await page.locator('#storage-valveMode').inputValue(),'auto');assert.equal(await page.locator('#storage-states tbody tr').count(),4);
  await page.locator('#storage-step').click();assert.equal(await page.locator('#storage-clock').textContent(),'10.0 s simulated');assert.doesNotMatch(await page.locator('#storage-status').textContent(),/LIMIT|TRIPPED/);
  const before=await page.locator('#storage-clock').textContent();await page.locator('#storage-ambient').fill('86');await page.locator('#storage-gain').fill('20');await page.locator('#storage-leakUA').fill('0.2');await page.locator('#storage-form button[type="submit"]').click();assert.equal(await page.locator('#storage-clock').textContent(),before);assert(await page.locator('#storage-error').isHidden());
  await page.locator('#temperature-unit').selectOption('C');assert.equal(await page.locator('#storage-ambient').inputValue(),'30');assert.equal(await page.locator('#storage-superheatTarget').inputValue(),'5');await page.locator('#temperature-unit').selectOption('F');assert.equal(await page.locator('#storage-ambient').inputValue(),'86');
  const pending=page.waitForEvent('download');await page.locator('#storage-export').click();const download=await pending,file=path.join(__dirname,'release-'+engine+'.csv');await download.saveAs(file);const rows=csvRows(fs.readFileSync(file,'utf8')),header=rows.find(r=>r[0]==='Seconds'),samples=rows.slice(rows.indexOf(header)+1);assert(samples.every(r=>r.length===header.length),'CSV columns align');const last=samples.at(-1),at=key=>last[header.indexOf(key)];assert.equal(at('Ambient C'),'30');assert.equal(at('Room gain kW'),'20');assert.equal(at('Room leak UA kW/K'),'0.2');assert(Math.abs(Number(at('Seconds'))-10)<1e-8);
  const charge=Number(at('Charge kg'));assert(Math.abs(Number(at('Combined energy residual kJ')))<1e-6);assert(charge>0);
  await page.locator('#storage-ambient').fill('200');await page.locator('#storage-form button[type="submit"]').click();assert.match(await page.locator('#storage-error').textContent(),/Room boundaries/);assert.equal(await page.locator('#storage-clock').textContent(),before);await page.locator('#storage-ambient').fill('86');await page.locator('#storage-form button[type="submit"]').click();assert(await page.locator('#storage-error').isHidden());
  await page.locator('#storage-start').click();await page.clock.runFor(1000);assert(await page.locator('#storage-pause').isEnabled());await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});assert(await page.locator('#storage-pause').isDisabled());await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:false});});
  await page.locator('#pressure-unit').selectOption('bara');await page.locator('#profile-new').click();await page.locator('#profile-name').fill('Release trip evidence');await page.locator('#profile-highTrip').fill('3');
  await page.locator('#profile-save').click();assert(await page.locator('#profile-error').isHidden());await page.locator('#profile-use').click();
  for(const speed of ['1','10','60']){await page.locator('#storage-example').click();await page.locator('#storage-speed').selectOption(speed);await page.locator('#storage-start').click();await page.clock.runFor(1000);assert.match(await page.locator('#storage-status').textContent(),/TRIPPED.*High discharge pressure/);assert.equal(await page.locator('#storage-clock').textContent(),'0.0 s simulated');assert(await page.locator('#storage-pause').isDisabled());}
  const faultDownload=page.waitForEvent('download');await page.locator('#storage-export').click();const fd=await faultDownload;await fd.saveAs(file);const faultRows=csvRows(fs.readFileSync(file,'utf8')),fh=faultRows.find(r=>r[0]==='Seconds'),fault=faultRows.at(-1),snapshot=JSON.parse(fault[fh.indexOf('Fault snapshot JSON SI')]);assert.equal(snapshot.kind,'equipment');assert.equal(snapshot.seconds,0);assert.equal(snapshot.readings.condensing,12);assert(Math.abs(snapshot.limits.highTrip-3)<1e-6);assert.equal(snapshot.attemptedReadings,null);
  await page.locator('#storage-compressorOn').uncheck();await page.locator('#storage-form button[type="submit"]').click();await page.locator('#storage-clear').click();await page.locator('#storage-step').click();assert.doesNotMatch(await page.locator('#storage-status').textContent(),/TRIPPED/);
  await page.locator('#tab-validation').click();assert.equal(await page.locator('#integration-table tr').count(),24);assert.match(await page.locator('#integration-summary').textContent(),/combined energy residual/);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.setViewportSize({width:390,height:844});await page.locator('#tab-live').click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.locator('#storage-lab').screenshot({path:path.join(__dirname,'release-'+engine+'-mobile.png')});assert.deepEqual(errors,[]);
  const offline=await context.newPage(),offlineErrors=[];offline.on('pageerror',e=>offlineErrors.push(e.message));await offline.route(/^https?:/,route=>route.abort());await offline.setContent(fs.readFileSync(path.resolve(__dirname,'../index.html'),'utf8'));await offline.locator('#tab-live').click();await offline.locator('#storage-example').click();await offline.locator('#storage-step').click();assert.equal(await offline.locator('#storage-clock').textContent(),'10.0 s simulated');assert(await offline.locator('#storage-error').isHidden());assert.deepEqual(offlineErrors,[]);
  console.log('PASS: '+engine+' release on iPad viewport, tab navigation, automatic DX setup, live boundaries / SI CSV, atomic rejection, background pause, trips at all speeds, fault snapshots, recovery, validation view, mobile overflow and standalone HTML with network blocked.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
