const assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const {chromium,webkit,devices}=require('playwright'),{launchOptions}=require('./browser-helpers.cjs');
const P=require('../equipment-profiles'),e=require('../engine').createEngine(require('../properties.json')),model=require('../storage-engine').createStorage(e,P);
(async()=>{
 const browser=await (process.env.TEST_BROWSER==='webkit'?webkit:chromium).launch(process.env.TEST_BROWSER==='webkit'?{headless:true}:launchOptions);
 try{
  const page=await browser.newPage({...devices['iPad (gen 7)']}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.clock.install();await page.goto(process.env.TEST_URL);await page.locator('#tab-live').click();
  assert.match(await page.locator('#schematic-status').textContent(),/Initialize/);assert.equal(await page.locator('[data-reading="receiver-pressure"]').textContent(),'—');
  await page.locator('#storage-example').click();
  const initial=model.create(P.DEFAULT,{}, {circuit:'circulating',thermalMode:'air',compressorOn:true,speed:.7,valveMode:'auto'}),r=model.record(initial),c=model.observeCompressor(initial);
  const level=page.locator('[data-level="receiver"]');assert(Math.abs(Number(await level.getAttribute('data-fraction'))-r.vessels.receiver.liquidVolumeFraction)<1e-12);
  assert.equal(await page.locator('[data-reading="receiver-pressure"]').textContent(),((r.vessels.receiver.p-1.01325)*14.503773773).toFixed(2)+' psig');
  assert.equal(await page.locator('[data-reading="discharge-temperature"]').textContent(),'Discharge: '+(c.dischargeTemperature*1.8+32).toFixed(2)+' °F');
  assert.match(await page.locator('[data-reading="compressor-status"]').textContent(),/PAUSED/);
  await page.locator('[data-component="feed"]').focus();await page.keyboard.press('Enter');assert.equal(await page.locator('[data-component="feed"]').getAttribute('aria-pressed'),'true');assert.match(await page.locator('#schematic-detail').textContent(),/lagged sensed/);
  await page.locator('#storage-step').click();assert.match(await page.locator('#schematic-status').textContent(),/^10.0 s/);assert.match(await page.locator('#schematic-flow-note').textContent(),/accepted average flow/);assert.equal(await page.locator('#schematic-graphic svg').getAttribute('class'),'schematic-still');
  await page.setViewportSize({width:1520,height:1100});await page.locator('#storage-schematic').screenshot({path:path.join(__dirname,'schematic-desktop.png')});await page.locator('[data-inspect="receiver"]').click();assert.equal(await page.locator('[data-component="receiver"]').getAttribute('aria-pressed'),'true');
  const fraction=await level.getAttribute('data-fraction');await page.locator('#temperature-unit').selectOption('C');await page.locator('#pressure-unit').selectOption('bara');assert.match(await page.locator('[data-reading="receiver-pressure"]').textContent(),/bar\(a\)/);assert.match(await page.locator('[data-reading="receiver-temperature"]').textContent(),/°C/);assert.equal(await level.getAttribute('data-fraction'),fraction);
  await page.locator('#storage-start').click();await page.clock.runFor(500);assert.equal(await page.locator('#schematic-graphic svg').getAttribute('class'),'');await page.locator('#schematic-motion').click();assert.equal(await page.locator('#schematic-graphic svg').getAttribute('class'),'schematic-still');await page.locator('#storage-pause').click();
  await page.locator('#storage-compressorOn').uncheck();await page.locator('#storage-form button[type="submit"]').click();assert.equal(await page.locator('[data-reading="compressor-status"]').textContent(),'OFF');assert.equal(await page.locator('[data-port="discharge"]').getAttribute('data-active'),'false');assert.match(await page.locator('[data-reading="receiver-pressure"]').textContent(),/\d/);
  await page.locator('#storage-drainEnabled').uncheck();await page.locator('#storage-form button[type="submit"]').click();assert.equal(await page.locator('[data-port="drain"]').getAttribute('data-active'),'false');
  await page.locator('#storage-valveMode').selectOption('closed');await page.locator('#storage-form button[type="submit"]').click();await page.locator('[data-component="feed"]').click();assert.match(await page.locator('#schematic-detail').textContent(),/0.00%/);assert.match(await page.locator('#schematic-detail').textContent(),/takes time/);
  await page.locator('#profile-new').click();await page.locator('#profile-name').fill('Schematic trip test');await page.locator('#profile-highTrip').fill('10');await page.locator('#profile-save').click();await page.locator('#profile-use').click();assert.match(await page.locator('#schematic-status').textContent(),/Initialize/);await page.locator('#storage-example').click();await page.locator('#storage-step').click();assert.equal(await page.locator('[data-reading="compressor-status"]').textContent(),'STOPPED');assert.match(await page.locator('#schematic-status').textContent(),/High discharge pressure/);assert.equal(await page.locator('[data-port="discharge"]').getAttribute('data-active'),'false');
  await page.locator('#profile-select').selectOption('default');await page.locator('#profile-use').click();await page.locator('#storage-circuit').selectOption('closed');await page.locator('#storage-compressorOn').uncheck();await page.locator('#storage-initialize').click();assert.equal(await page.locator('[data-port="feed"]').getAttribute('data-active'),'false');await page.locator('[data-component="outlet"]').click();assert.match(await page.locator('#schematic-detail').textContent(),/inactive in isolated storage/);
  await page.locator('#storage-example').click();await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.locator('.schematic-flow').first().evaluate(el=>getComputedStyle(el).animationName),'none');
  for(const viewport of [{width:1024,height:1366},{width:768,height:1024},{width:390,height:844}]){await page.setViewportSize(viewport);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert(await page.locator('[data-component="compressor"]').isVisible());}
  await page.locator('#storage-schematic').screenshot({path:path.join(__dirname,'schematic-mobile.png')});
  const offline=await browser.newPage();await offline.route(/^https?:/,route=>route.abort());await offline.setContent(fs.readFileSync(path.resolve(__dirname,'../index.html'),'utf8'));await offline.locator('#tab-live').click();await offline.locator('#storage-example').click();await offline.locator('#storage-step').click();assert.match(await offline.locator('#schematic-status').textContent(),/^10.0 s/);assert.deepEqual(errors,[]);
  console.log('PASS: model/display agreement, levels, discharge temperature, units, keyboard inspection, playback/motion, off pressure, blocked drain, valve lag, trips, profile reset, isolated mode, reduced motion, tablet/mobile and offline schematic.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
