const assert=require('node:assert/strict'),P=require('../equipment-profiles');
const e=require('../engine').createEngine(require('../properties.json')),make=n=>require('../storage-engine').createStorage(e,P,n),d=make();
const max={liquidPressureBar:0,vaporPressureBar:0,mixturePressureBar:0,temperatureK:0};
for(const r of require('./storage-reference.json').states){
 const a=e.stateDU(r.rho,r.u);assert(Math.abs(a.densityResidual)<1e-8);assert(Math.abs(a.energyResidual)<1e-6);
 assert.equal(a.phase,r.kind==='liquid'?'Subcooled liquid':r.kind==='vapor'?'Superheated vapor':'Liquid + vapor');
 const key=r.kind+'PressureBar';max[key]=Math.max(max[key],Math.abs(a.p-r.p));max.temperatureK=Math.max(max.temperatureK,Math.abs(a.T-r.T));
 assert(Math.abs(a.p-r.p)<(r.kind==='liquid'?.05:.002));assert(Math.abs(a.T-r.T)<.02);
}
for(const [p,T,kind]of [[12,20,'liquid'],[3,-15,'liquid'],[2.5,5,'vapor']]){const a=e.statePT(p,T,kind);assert(Math.abs(e.ph(p,a.h).T-T)<1e-6);assert(Math.abs(e.ps(p,a.s).T-T)<1e-6);const b=e.stateDU(a.rho,a.h-100*p/a.rho);assert(Math.abs(b.p-p)<1e-5);}
assert.throws(()=>e.stateDU(0,500),/positive/);assert.throws(()=>e.stateDU(1,10000),/outside/);assert.throws(()=>e.stateMVU(1,0,100));
for(const phase of ['vapor','liquid']){const sat=e.sat(12),state=e.statePT(12,sat.T,phase==='liquid'?'liquid':undefined);assert.equal(d.phaseOutlet(state,phase).phase,state.phase);}
const check=s=>{const r=d.record(s);assert(Math.abs(r.massResidualKg)<1e-9);assert(Math.abs(r.energyResidualKJ)<1e-6);assert(Object.values(s.vessels).every(v=>v.massKg>0));assert(Object.values(s.states).every(v=>v.p>=.3&&v.p<=35&&Math.abs(v.energyResidual)<1e-6));return r;};
const sealed=d.create(P.DEFAULT),original=JSON.stringify(sealed.vessels);d.advance(sealed,60);assert.equal(JSON.stringify(sealed.vessels),original);assert.equal(sealed.states.evaporator.p,2.5);check(sealed);
const heated=d.create(P.DEFAULT,{}, {evaporatorHeat:5});d.advance(heated,10);assert(heated.states.evaporator.p>2.5);assert.equal(heated.states.receiver.p,12);assert(Math.abs(check(heated).externalHeatKJ-50)<1e-8);
for(const [fill,heat,phase]of [[1,.5,'Subcooled liquid'],[0,.5,'Superheated vapor']]){const p=P.copy(P.DEFAULT);p.inventory.initialization.liquidFractions.receiver=fill;const s=d.create(p,{}, {receiverHeat:heat});d.advance(s,10);assert.equal(s.states.receiver.phase,phase);check(s);d.update(s,{receiverHeat:-heat});d.advance(s,10);assert(Math.abs(s.vessels.receiver.internalEnergyKJ-s.rows[0].vessels.receiver.internalEnergyKJ)<1e-7);check(s);}
const boilProfile=P.copy(P.DEFAULT);boilProfile.inventory.initialization.liquidFractions.evaporator=.001;const boiled=d.create(boilProfile,{}, {evaporatorHeat:5});d.advance(boiled,20);assert.equal(boiled.states.evaporator.phase,'Superheated vapor');check(boiled);d.update(boiled,{evaporatorHeat:-5});d.advance(boiled,10);assert.equal(boiled.states.evaporator.phase,'Liquid + vapor');check(boiled);
const pump=d.create(P.DEFAULT,{}, {compressorOn:true});d.advance(pump,5);assert(pump.vessels.evaporator.massKg<pump.rows[0].vessels.evaporator.massKg);assert(pump.vessels.condenser.massKg>pump.rows[0].vessels.condenser.massKg);assert(pump.states.evaporator.p<2.5);assert(pump.states.condenser.p>12);assert(check(pump).electricalKWh>0);const before=d.record(pump);d.update(pump,{compressorOn:false});d.advance(pump,5);assert.equal(pump.electricalKWh,before.electricalKWh);assert.equal(pump.vessels.evaporator.massKg,before.vessels.evaporator.massKg);assert(pump.states.evaporator.p>0);check(pump);
const run=(model,chunk,seconds=20)=>{const s=model.create(P.DEFAULT,{}, {thermalMode:'air',compressorOn:true});for(let t=0;t<seconds;t+=chunk)model.advance(s,chunk);return s;};
const a=run(d,20),b=run(d,1),refined=run(make({maxStep:.05}),20);assert.equal(a.states.evaporator.p,b.states.evaporator.p);assert.equal(a.electricalKWh,b.electricalKWh);assert(Math.abs(a.states.evaporator.p-refined.states.evaporator.p)<.001);assert(Math.abs(a.T-refined.T)<.0001);assert(Math.abs(a.electricalKWh/refined.electricalKWh-1)<.0001);assert(a.T<15);assert(a.rejectedSteps>0);check(a);check(refined);
const tripProfile=P.copy(P.DEFAULT);tripProfile.equipment.highTrip=3;const trip=d.create(tripProfile,{}, {compressorOn:true});d.advance(trip,10);assert.equal(trip.fault.kind,'equipment');assert.equal(trip.time,0);assert.equal(trip.pending,0);assert.equal(trip.fault.readings.condensing,trip.states.condenser.p);check(trip);d.advance(trip,100);assert.equal(trip.time,0);d.update(trip,{compressorOn:false});d.clearFault(trip);d.advance(trip,1);assert(Math.abs(trip.time-1)<1e-8);
const stops=[1,60].map(chunk=>{const s=d.create(P.DEFAULT,{}, {compressorOn:true});while(!s.fault)d.advance(s,chunk);return s;});assert.equal(stops[0].time,stops[1].time);assert.deepEqual(stops[0].fault,stops[1].fault);assert.equal(stops[0].fault.seconds,stops[0].time);
const allLiquid=P.copy(P.DEFAULT);allLiquid.inventory.initialization.liquidFractions.receiver=1;const limited=d.create(allLiquid,{}, {receiverHeat:100});d.advance(limited,10);assert.equal(limited.fault.kind,'domain');assert.equal(limited.pending,0);check(limited);const frozen=JSON.stringify(limited.vessels);d.advance(limited,10);assert.equal(JSON.stringify(limited.vessels),frozen);
const transferred=d.create(P.DEFAULT);d.advance(transferred,10,[{from:'receiver',to:'evaporator',phase:'liquid',massFlow:.01}]);assert(Math.abs(transferred.vessels.receiver.massKg-transferred.rows[0].vessels.receiver.massKg+.1)<1e-8);assert(Math.abs(transferred.vessels.evaporator.massKg-transferred.rows[0].vessels.evaporator.massKg-.1)<1e-8);check(transferred);
const ports=d.portRates(a.states,[{from:'receiver',to:'evaporator',phase:'liquid',massFlow:.01}]);assert.equal(ports.rates.receiver.mass+ports.rates.evaporator.mass,0);assert.equal(ports.rates.receiver.energy+ports.rates.evaporator.energy,0);assert.equal(ports.fluidWork,0);
const wet=P.copy(P.DEFAULT);wet.inventory.initialization.liquidFractions.evaporator=1;const invalidSuction=d.create(wet,{}, {compressorOn:true});d.advance(invalidSuction,1);assert.equal(invalidSuction.fault.kind,'domain');assert.equal(invalidSuction.time,0);check(invalidSuction);
const missing=P.copy(P.DEFAULT);missing.inventory.initialization=null;assert.throws(()=>d.create(missing),/not configured/);assert.throws(()=>d.update(a,{receiverHeat:NaN}));
console.log(JSON.stringify({passed:true,directPropertyStates:90,maxErrors:max,massResidualKg:check(a).massResidualKg,energyResidualKJ:check(a).energyResidualKJ,refinementPressureBar:Math.abs(a.states.evaporator.p-refined.states.evaporator.p)},null,2));
