const assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const {chromium}=require('playwright'),{launchOptions}=require('./browser-helpers.cjs');
(async()=>{
 const browser=await chromium.launch(launchOptions);
 try{
  const page=await browser.newPage({acceptDownloads:true,viewport:{width:1280,height:950}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.clock.install();await page.goto(process.env.TEST_URL);await page.locator('#tab-live').click();await page.locator('#storage-initialize').click();
  assert(await page.locator('#storage-error').isHidden());assert.match(await page.locator('#storage-status').textContent(),/Default revision 3/);
  assert.match(await page.locator('#storage-states').textContent(),/psig/);assert.match(await page.locator('#storage-states').textContent(),/°F/);
  const initial=await page.locator('#storage-states').textContent();await page.locator('#storage-step').click();assert.equal(await page.locator('#storage-clock').textContent(),'10.0 s simulated');assert.equal(await page.locator('#storage-states').textContent(),initial);
  await page.locator('#storage-evaporatorHeat').fill('5');await page.locator('#storage-form button[type="submit"]').click();await page.locator('#storage-step').click();assert.notEqual(await page.locator('#storage-states').textContent(),initial);assert.match(await page.locator('#storage-balance').textContent(),/50.000 kJ/);
  await page.locator('#temperature-unit').selectOption('C');await page.locator('#pressure-unit').selectOption('bara');assert.match(await page.locator('#storage-states').textContent(),/bar\(a\)/);assert.match(await page.locator('#storage-states').textContent(),/°C/);
  const pending=page.waitForEvent('download');await page.locator('#storage-export').click();const download=await pending,file=path.join(__dirname,'storage-results.csv');await download.saveAs(file);const csv=fs.readFileSync(file,'utf8');assert.match(csv,/Combined energy residual kJ/);assert.match(csv,/evaporator bar absolute/);assert.match(csv,/"20/);
  await page.locator('#storage-evaporatorHeat').fill('0');await page.locator('#storage-compressorOn').check();await page.locator('#storage-initialize').click();await page.locator('#storage-step').click();assert.match(await page.locator('#storage-status').textContent(),/TRIPPED.*High discharge temperature/);assert(await page.locator('#storage-states').isVisible());const stopped=await page.locator('#storage-clock').textContent();await page.locator('#storage-step').click();assert.equal(await page.locator('#storage-clock').textContent(),stopped);await page.locator('#storage-start').click();assert(await page.locator('#storage-error').isVisible());
  await page.locator('#storage-compressorOn').uncheck();await page.locator('#storage-form button[type="submit"]').click();await page.locator('#storage-clear').click();await page.locator('#storage-step').click();assert.doesNotMatch(await page.locator('#storage-status').textContent(),/TRIPPED/);assert.notEqual(await page.locator('#storage-clock').textContent(),stopped);
  await page.locator('#storage-initialize').click();await page.locator('#storage-start').click();await page.clock.runFor(1000);assert(await page.locator('#storage-pause').isEnabled());await page.locator('#live-start').click();assert(await page.locator('#storage-pause').isDisabled());await page.locator('#live-pause').click();
  await page.locator('#storage-start').click();await page.clock.runFor(1000);await page.locator('#storage-pause').click();assert(await page.locator('#storage-start').isEnabled());
  await page.locator('#profile-new').click();await page.locator('#profile-name').fill('No storage initialization');await page.locator('#profile-inventory summary').click();await page.locator('#profile-init-mode').selectOption('none');await page.locator('#profile-save').click();await page.locator('#profile-use').click();assert.match(await page.locator('#storage-status').textContent(),/equipment changed/);assert(await page.locator('#storage-export').isDisabled());await page.locator('#storage-initialize').click();assert.match(await page.locator('#storage-error').textContent(),/not configured/);await page.locator('#live-step').click();assert(await page.locator('#live-error').isHidden());
  await page.locator('#profile-select').selectOption('default');await page.locator('#profile-use').click();await page.locator('#storage-initialize').click();await page.locator('#storage-thermalMode').selectOption('air');await page.locator('#storage-step').click();assert(await page.locator('#storage-error').isHidden());assert.match(await page.locator('#storage-status').textContent(),/air boundaries/);
  await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(__dirname,'storage-mobile.png'),fullPage:true});assert.deepEqual(errors,[]);
  console.log('PASS: storage initialize/sealed/heating, off pressures, units, CSV, trips/recovery, playback isolation, unavailable initialization, air coupling and mobile layout.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
