const assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const {chromium,webkit,devices}=require('playwright'),{launchOptions}=require('./browser-helpers.cjs');
(async()=>{
 const which=process.env.TEST_BROWSER==='webkit'?'webkit':'chromium',browser=await (which==='webkit'?webkit:chromium).launch(which==='webkit'?{headless:true}:launchOptions);
 try{
  const page=await browser.newPage({...devices['iPad (gen 7)'],acceptDownloads:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{Array.prototype.at=undefined;});await page.clock.install();await page.goto(process.env.TEST_URL);await page.locator('#tab-live').click();
  assert(await page.locator('#training-load').isEnabled());await page.locator('#training-load').click();assert.match(await page.locator('#training-status').textContent(),/In progress/);await page.locator('#training-hint').click();assert(await page.locator('#training-hint-text').isVisible());await page.locator('#training-answer').selectOption('1');await page.locator('#training-check').click();assert.match(await page.locator('#training-feedback').textContent(),/Try again/);await page.locator('#training-answer').selectOption('0');await page.locator('#training-check').click();
  for(let i=0;i<12&&await page.locator('#training-advance').isEnabled();i++)await page.locator('#training-advance').click();assert.match(await page.locator('#training-status').textContent(),/Objectives completed/);assert(await page.locator('#training-debrief').isVisible());assert(await page.locator('#storage-pause').isDisabled());
  const file=path.join(__dirname,'training-'+which+'.json'),download=page.waitForEvent('download');await page.locator('#training-export').click();await (await download).saveAs(file);const report=JSON.parse(fs.readFileSync(file,'utf8'));assert.equal(report.attempt.status,'completed');assert.equal(report.attempt.exercise,'startup');assert.equal(report.attempt.appVersion,'0.5.0');assert(report.attempt.goals.every(g=>g.met));assert(report.history.events.some(e=>e.type==='training'));assert.equal(report.history.initialRoom.initial,15);
  // Selecting a new lesson previews it without relabeling or mutating the retained attempt.
  await page.locator('#training-select').selectOption('load');assert.match(await page.locator('#training-selected-title').textContent(),/Room load increase/);assert.match(await page.locator('#training-attempt-title').textContent(),/Retained attempt.*DX startup/);assert(await page.locator('#training-selection-note').isVisible());assert.match(await page.locator('#training-question').textContent(),/resolved evaporator outlet/);
  const retainedDownload=page.waitForEvent('download');await page.locator('#training-export').click();await (await retainedDownload).saveAs(file);assert.deepEqual(JSON.parse(fs.readFileSync(file,'utf8')),report);
  await page.locator('#training-reset').click();assert.match(await page.locator('#training-selected-title').textContent(),/Room load increase/);assert.match(await page.locator('#training-attempt-title').textContent(),/Current attempt.*DX startup/);assert.equal(await page.locator('#training-answer').inputValue(),'');await page.locator('#training-end').click();
  for(const id of ['load','restriction','tuning']){
   await page.locator('#training-select').selectOption(id);await page.locator('#training-load').click();assert.equal(await page.locator('#storage-circuit').inputValue(),'circulating');assert.equal(await page.locator('#storage-compressorSpeed').inputValue(),'70');await page.locator('#training-answer').selectOption('0');await page.locator('#training-check').click();await page.locator('#training-disturbance').click();assert(await page.locator('#training-error').isHidden());
   const boundary=await page.locator('#storage-gain').inputValue();if(id==='load')assert.equal(boundary,'20');if(id==='restriction'){assert.equal(await page.locator('#storage-manualOpening').inputValue(),'2');assert.equal(await page.locator('#storage-valveMode').inputValue(),'manual');}if(id==='tuning'){assert(Math.abs(Number(await page.locator('#storage-superheatTarget').inputValue())-12.6)<1e-8);assert.match(await page.locator('#training-status').textContent(),/began at 120.000/);}
   for(let i=0;i<20&&await page.locator('#training-advance').isEnabled();i++)await page.locator('#training-advance').click();assert.match(await page.locator('#training-status').textContent(),/Objectives completed/,id);assert(await page.locator('#storage-error').isHidden());
  }
  // Completion occurs within the timer batch at every supported playback speed.
  for(const speed of ['1','10','60']){
   await page.locator('#training-select').selectOption('restriction');await page.locator('#training-load').click();assert(await page.locator('#training-selection-note').isHidden());await page.locator('#training-answer').selectOption('0');await page.locator('#training-check').click();await page.locator('#training-disturbance').click();await page.locator('#storage-speed').selectOption(speed);await page.locator('#training-run').click();await page.clock.runFor(speed==='1'?12000:1500);
   assert.match(await page.locator('#training-status').textContent(),/Objectives completed/,'Speed '+speed);assert.equal(await page.locator('#storage-clock').textContent(),'40.0 s simulated');assert(await page.locator('#storage-pause').isDisabled());assert.doesNotMatch(await page.locator('#storage-status').textContent(),/TRIPPED/);
   const completedDownload=page.waitForEvent('download');await page.locator('#training-export').click();await (await completedDownload).saveAs(file);const completed=JSON.parse(fs.readFileSync(file,'utf8'));assert.equal(completed.attempt.status,'completed');assert(Math.abs(completed.final.seconds-40)<1e-8);assert(Math.abs(completed.attempt.endedAt-completed.final.seconds)<1e-8);assert.equal(completed.final.fault,null);
   if(speed==='60'){
    await page.locator('#storage-step').click();await page.locator('#storage-step').click();assert.match(await page.locator('#storage-status').textContent(),/TRIPPED/);const frozenDownload=page.waitForEvent('download');await page.locator('#training-export').click();await (await frozenDownload).saveAs(file);assert.deepEqual(JSON.parse(fs.readFileSync(file,'utf8')),completed,'Free exploration must not rewrite the completed report');
   }
  }
  await page.locator('#training-reset').click();await page.locator('#training-disturbance').click();await page.locator('#training-run').click();await page.clock.runFor(1500);assert.match(await page.locator('#training-status').textContent(),/Stopped before completion/);assert.match(await page.locator('#storage-status').textContent(),/TRIPPED/);assert(await page.locator('#storage-pause').isDisabled());
  await page.locator('#training-select').selectOption('hot');await page.locator('#training-load').click();await page.locator('#training-answer').selectOption('0');await page.locator('#training-check').click();await page.locator('#training-disturbance').click();assert.equal(await page.locator('#storage-ambient').inputValue(),'104');for(let i=0;i<12&&await page.locator('#training-advance').isEnabled();i++)await page.locator('#training-advance').click();assert.match(await page.locator('#storage-status').textContent(),/High discharge temperature/);assert(await page.locator('#training-clear').isDisabled());await page.locator('#training-restore').click();assert(!(await page.locator('#storage-compressorOn').isChecked()));assert.equal(await page.locator('#storage-ambient').inputValue(),'77');await page.locator('#training-clear').click();await page.locator('#training-advance').click();assert.match(await page.locator('#training-status').textContent(),/Objectives completed/);assert.match(await page.locator('#training-debrief').textContent(),/not qualification/);
  await page.locator('#training-reset').click();assert.match(await page.locator('#training-status').textContent(),/In progress/);assert.equal(await page.locator('#training-objectives .met').count(),0);await page.locator('#training-end').click();assert.match(await page.locator('#training-status').textContent(),/Ended by learner/);
  await page.locator('#training-select').selectOption('startup');await page.locator('#training-load').click();await page.locator('#storage-compressorSpeed').fill('80');await page.locator('#storage-form button[type="submit"]').click();assert.match(await page.locator('#training-status').textContent(),/Controls differ/);assert(await page.locator('#training-debrief').isVisible());
  await page.locator('#training-reset').click();await page.locator('#temperature-unit').selectOption('C');await page.locator('#pressure-unit').selectOption('bara');assert.match(await page.locator('#training-status').textContent(),/In progress/);await page.locator('#storage-initialize').click();assert.match(await page.locator('#training-status').textContent(),/reinitialized/);
  await page.locator('#profile-new').click();await page.locator('#profile-name').fill('Custom exercise guard');await page.locator('#profile-save').click();await page.locator('#profile-use').click();assert(await page.locator('#training-load').isDisabled());assert.match(await page.locator('#training-status').textContent(),/Apply Default/);await page.locator('#profile-select').selectOption('default');await page.locator('#profile-use').click();assert(await page.locator('#training-load').isEnabled());
  await page.locator('#training-select').selectOption('startup');await page.locator('#training-load').click();await page.locator('#training-run').click();await page.clock.runFor(500);assert.match(await page.locator('#training-run').textContent(),/Pause/);await page.locator('#training-run').click();assert(await page.locator('#storage-pause').isDisabled());await page.locator('#training-hint').focus();await page.keyboard.press('Enter');assert.equal(await page.locator('#training-hint').getAttribute('aria-expanded'),'true');
  for(const viewport of [{width:1024,height:1366},{width:768,height:1024},{width:390,height:844}]){await page.setViewportSize(viewport);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert(await page.locator('#training-advance').isVisible());}await page.locator('#storage-training').screenshot({path:path.join(__dirname,'training-'+which+'-mobile.png')});
  const offline=await browser.newPage();offline.on('pageerror',e=>errors.push(e.message));await offline.route(/^https?:/,r=>r.abort());await offline.setContent(fs.readFileSync(path.resolve(__dirname,'../index.html'),'utf8'));await offline.locator('#tab-live').click();await offline.locator('#training-load').click();await offline.locator('#training-advance').click();assert.match(await offline.locator('#training-status').textContent(),/In progress/);assert.deepEqual(errors,[]);
  console.log('PASS: '+which+' five measured exercises, accepted-boundary completion at 1/10/60×, missing-reflection stop, selected/retained separation, frozen export, warmup, real disturbances, reflection/hints, hot stop/off continuation, debrief/export, reset/end, wrong-control and equipment guards, units, playback, keyboard, tablet/mobile, legacy browser and offline training.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
