const assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const {chromium}=require('playwright'),{launchOptions}=require('./browser-helpers.cjs');
(async()=>{const browser=await chromium.launch(launchOptions);try{
 const page=await browser.newPage({acceptDownloads:true,viewport:{width:1024,height:1366}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(process.env.TEST_URL);await page.locator('#tab-live').click();
 await page.locator('#storage-circuit').selectOption('circulating');await page.locator('#storage-thermalMode').selectOption('air');await page.locator('#storage-compressorOn').check();await page.locator('#storage-compressorSpeed').fill('70');await page.locator('#storage-valveMode').selectOption('auto');await page.locator('#storage-initialize').click();assert(await page.locator('#storage-error').isHidden());assert.equal(await page.locator('#storage-states tbody tr').count(),4);assert.match(await page.locator('#storage-flows').textContent(),/9.00 °F Δ/);
 await page.locator('#storage-step').click();assert(await page.locator('#storage-error').isHidden());assert.doesNotMatch(await page.locator('#storage-status').textContent(),/MODEL LIMIT|TRIPPED/);assert.match(await page.locator('#storage-flows').textContent(),/feed flow.*kg\/s/);
 await page.locator('#temperature-unit').selectOption('C');assert.equal(await page.locator('#storage-superheatTarget').inputValue(),'5');assert.equal(await page.locator('#storage-dunit').textContent(),'K');await page.locator('#temperature-unit').selectOption('F');assert.equal(await page.locator('#storage-superheatTarget').inputValue(),'9');
 await page.locator('#storage-manualOpening').fill('45');await page.locator('#storage-valveMode').selectOption('manual');await page.locator('#storage-drainEnabled').uncheck();await page.locator('#storage-form button[type="submit"]').click();await page.locator('#storage-step').click();assert.match(await page.locator('#storage-flows').textContent(),/drain flow0.00000 kg\/s/);
 const downloadWait=page.waitForEvent('download');await page.locator('#storage-export').click();const download=await downloadWait,file=path.join(__dirname,'valves-results.csv');await download.saveAs(file);const csv=fs.readFileSync(file,'utf8');assert.match(csv,/Actual superheat K/);assert.match(csv,/outlet bar absolute/);assert.match(csv,/Drain gravity energy kJ/);assert.match(csv,/"manual"/);
 await page.locator('#storage-circuit').selectOption('closed');await page.locator('#storage-form button[type="submit"]').click();assert.match(await page.locator('#storage-error').textContent(),/Reinitialize/);await page.locator('#storage-circuit').selectOption('circulating');
 await page.locator('#profile-new').click();await page.locator('#profile-name').fill('Valve geometry');await page.locator('#profile-connections summary').click();await page.locator('#profile-connection-feedAreaM2').fill('0.00003');await page.locator('#profile-connection-outletInitialSuperheatK').fill('7');await page.locator('#profile-save').click();assert(await page.locator('#profile-error').isHidden());await page.locator('#profile-use').click();await page.locator('#storage-initialize').click();assert.match(await page.locator('#storage-flows').textContent(),/12.60 °F Δ/);
 await page.locator('#profile-edit').click();await page.locator('#profile-connections-enabled').uncheck();await page.locator('#profile-save').click();await page.locator('#profile-use').click();await page.locator('#storage-initialize').click();assert.match(await page.locator('#storage-error').textContent(),/Configure valve/);await page.locator('#storage-circuit').selectOption('closed');await page.locator('#storage-compressorOn').uncheck();await page.locator('#storage-initialize').click();assert(await page.locator('#storage-error').isHidden());assert.equal(await page.locator('#storage-states tbody tr').count(),3);
 await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(__dirname,'valves-mobile.png'),fullPage:true});assert.deepEqual(errors,[]);console.log('PASS: connected circuit, real outlet superheat, Fahrenheit deltas, manual feed / drain controls, CSV, geometry reset, editable profiles and mobile layout.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
