const assert=require('node:assert/strict'),P=require('../equipment-profiles'),e=require('../engine').createEngine(require('../properties.json'));
const v=require('../valve-engine').createValves(e),make=n=>require('../storage-engine').createStorage(e,P,n),d=make();
const up=e.statePX(12,0),full=v.liquid(up,2.5,2e-5,1,.8,1.5),partial=v.liquid(up,2.5,2e-5,.5,.8,1.5);
assert(full.choked);assert.equal(full.massFlow,v.liquid(up,.5,2e-5,1,.8,1.5).massFlow);assert(Math.abs(partial.massFlow/full.massFlow-.5**1.5)<1e-12);
assert.equal(v.liquid(up,13,2e-5).massFlow,0);assert.equal(v.liquid(up,2.5,2e-5,0).massFlow,0);assert.equal(v.liquid(up,12,2e-5).massFlow,0);assert(v.liquid(up,12,2e-5,1,.8,1,2).massFlow>0);
const flash=e.ph(2.5,up.h);assert(flash.x>0&&flash.x<1);assert.equal(flash.h,up.h);
const gas=e.statePT(5,e.sat(5).T+10),nozzle=v.vapor(gas,1,2e-4);assert(nozzle.choked);assert.equal(nozzle.massFlow,v.vapor(gas,.5,2e-4).massFlow);assert.equal(v.vapor(gas,6,2e-4).massFlow,0);assert(v.vapor(gas,4.9,2e-4).massFlow<nozzle.massFlow);
const base={valveMode:'auto',kp:.1,ki:.01,superheatTarget:5,manualOpening:.25};assert.equal(v.controller({opening:.5,sensor:30,integral:0},base,P.DEFAULT.connections,30).integral,0);assert.equal(v.controller({opening:.5,sensor:0,integral:0},base,P.DEFAULT.connections,0).integral,0);assert(v.controller({opening:0,sensor:10,integral:0},base,P.DEFAULT.connections,10).integral>0);
for(const version of [1,2]){const legacy=P.copy(P.DEFAULT);legacy.schemaVersion=version;if(version===1){legacy.futureVolumes=legacy.inventory.volumes;delete legacy.inventory;}const p=P.normalize(legacy);assert.equal(p.schemaVersion,3);assert.equal(p.connections,null);assert.equal(p.revision,legacy.revision);if(version===2){assert.deepEqual(p.inventory,legacy.inventory);assert.throws(()=>d.create(p,{}, {circuit:'circulating'}),/Configure valve/);assert(d.create(p));}}
for(const [key,[low,high]]of Object.entries(P.connectionBounds))for(const x of [NaN,low/2-1,high+1,'2']){const p=P.copy(P.DEFAULT);p.connections[key]=x;assert.throws(()=>P.normalize(p));}
const ops={circuit:'circulating',thermalMode:'air',compressorOn:true,speed:.7,valveMode:'auto'},check=s=>{const r=d.record(s);assert(!s.fault,s.fault?.message);assert(Math.abs(r.massResidualKg)<1e-8);assert(Math.abs(r.energyResidualKJ)<1e-6);assert(r.controller.opening>=0&&r.controller.opening<=1);return r;};
const s=d.create(P.DEFAULT,{},ops),isolated=d.create(P.DEFAULT);assert.equal(Object.keys(s.vessels).length,4);assert(Math.abs(s.vessels.evaporator.volumeM3+s.vessels.outlet.volumeM3-P.DEFAULT.inventory.volumes.evaporator)<1e-12);assert(Math.abs(s.initialMassKg-isolated.initialMassKg)<1e-12);assert(Math.abs(s.initialEnergyKJ-isolated.initialEnergyKJ)<1e-12);assert(Math.abs(check(s).flows.superheat-5)<1e-5);
const wetProfile=P.copy(P.DEFAULT);wetProfile.inventory.initialization.liquidFractions.evaporator=.95;assert.throws(()=>d.create(wetProfile,{},ops),/vapor space/);
const bad=P.copy(P.DEFAULT);bad.connections.outletInitialSuperheatK=0;const wet=d.create(bad,{}, {...ops,speed:1});d.advance(wet,1);assert.equal(wet.fault.kind,'domain');assert.match(wet.fault.message,/Wet compressor suction/);assert.equal(wet.time,0);assert(Math.abs(d.record(wet).energyResidualKJ)<1e-9);
for(let i=0;i<10;i++)d.advance(s,60);const r=check(s);assert(Math.abs(r.flows.superheat-5)<.1);assert(r.flows.feed.massFlow>0&&r.flows.drain.massFlow>0&&r.flows.vapor.massFlow>0);assert(r.gravityEnergyKJ>0);assert(r.T<15);assert(r.controller.sensor>0);assert(s.rejectedSteps>0);
const run=(model,chunk)=>{const s=model.create(P.DEFAULT,{},ops);for(let t=0;t<20;t+=chunk)model.advance(s,chunk);check(s);return s;};const a=run(d,20),b=run(d,1),c=run(make({maxStep:.05,tolerance:5e-6}),20);assert.deepEqual(a.vessels,b.vessels);assert.deepEqual(a.controller,b.controller);assert(Math.abs(a.states.outlet.p-c.states.outlet.p)<.001);assert(Math.abs(a.controller.opening-c.controller.opening)<.001);assert(Math.abs(a.electricalKWh/c.electricalKWh-1)<.001);
const actuator=d.create(P.DEFAULT,{}, {circuit:'circulating',valveMode:'manual',manualOpening:.5,drainEnabled:false});d.advance(actuator,1);assert(Math.abs(actuator.controller.opening-.5*(1-Math.exp(-.5)))<1e-5);assert.equal(d.record(actuator).flows.drain.massFlow,0);d.update(actuator,{valveMode:'closed'});const previous=actuator.controller.opening;d.advance(actuator,1);assert(actuator.controller.opening<previous);assert.equal(d.record(actuator).flows.command,0);assert.throws(()=>d.update(actuator,{circuit:'closed'}),/Reinitialize/);
const empty=P.copy(P.DEFAULT);empty.inventory.initialization.liquidFractions.receiver=0;empty.inventory.initialization.liquidFractions.condenser=0;const noLiquid=d.create(empty,{}, {circuit:'circulating',valveMode:'manual',manualOpening:1});const h=d.hydraulics(noLiquid,noLiquid.states);assert.equal(h.feed.massFlow,0);assert.equal(h.drain.massFlow,0);assert.match(h.feed.status,/unavailable/);
const fast=P.copy(P.DEFAULT);fast.connections.actuatorSeconds=.05;fast.connections.sensorSeconds=.05;const quick=d.create(fast,{}, {circuit:'circulating',valveMode:'manual',manualOpening:1,drainEnabled:false});d.advance(quick,1);check(quick);assert(Math.abs(quick.controller.opening-(1-Math.exp(-20)))<1e-6);
const frozen=JSON.stringify(wet);d.advance(wet,30);assert.equal(JSON.stringify(wet),frozen);
console.log(JSON.stringify({passed:true,connectedSeconds:r.seconds,superheatK:r.flows.superheat,massResidualKg:r.massResidualKg,energyResidualKJ:r.energyResidualKJ,refinementOutletPressureBar:Math.abs(a.states.outlet.p-c.states.outlet.p)},null,2));
